
# Correlating Specific Pollution Sources with Air Quality Level

Steffany Lara, Brisma Alvarez, Emiliano Ruiz and Daniel De Pool

*Instituto Tecnológico y de Estudios Superiores de Monterrey (ITESM)*

**Abstract**


The overall objective is to quantify and explain the relative contribution of specific pollution sources such as factories, airports, and vehicular traffic to criteria pollutant levels in Monterrey through multivariate time series analysis from monitoring stations, in order to prioritize mitigation and optimization actions for air quality management.

## Importing the Data

### Exploratory Analysis

With aim of comprehending the data for a better prediction, the information from all the datasets would be analyzed. At a glance, in this approach, information regarding gases concentration from 2020 to 2022 would be used just for exploratory analysis, so that, we'll understand how the quarantine and reduction of multiples industries and less traffic congestion impacted on the concentration of polluting gases. Also, information from 2023 to 2024 would be useful in this exploratory analysis. Furthermore, information regarding the dataset "Padrón Medio Ambiente" would be checked for understanding which places have the most concurrency and the models that are more common in all of those places.

In [2]:
#Importar librerías
import pandas as pd

In [3]:
#First, we will joing all the databases in the same format: an excel with multiple sheets, every sheet cointains information regarding a certain station.,


#año 2020 y 2021 

db_2020_2021 = pd.read_excel("Bases_Datos/DATOS HISTÓRICOS 2020_2021_TODAS ESTACIONES.xlsx",sheet_name=None) 
db_2022_2023 = pd.read_excel("Bases_Datos/DATOS HISTÓRICOS 2022_2023_TODAS ESTACIONES.xlsx",sheet_name=None)
db_2023_2024 = pd.read_excel("Bases_Datos/DATOS HISTÓRICOS 2023_2024_TODAS ESTACIONES_ITESM-2.xlsx",sheet_name=None)

In [4]:
print(db_2020_2021.keys())
print(db_2022_2023.keys())
print(db_2023_2024.keys())

dict_keys(['SURESTE', 'NORESTE', 'CENTRO', 'NOROESTE', 'SUROESTE', 'NOROESTE2', 'NORTE', 'SUROESTE2', 'SURESTE2', 'SURESTE3', 'SUR', 'NORTE2', 'NORESTE2', 'NORESTE3', 'NOROESTE3', 'CATÁLOGO'])
dict_keys(['SURESTE', 'NORESTE', 'CENTRO', 'NOROESTE', 'SUROESTE', 'NOROESTE2', 'NORTE', 'SUROESTE2', 'SURESTE2', 'SURESTE3', 'SUR', 'NORTE2', 'NORESTE2', 'NORESTE3', 'NOROESTE3', 'CATÁLOGO'])
dict_keys(['Param_horarios_Estaciones', 'Hoja2'])

In [5]:
print(db_2022_2023['NOROESTE2'])

                     date    CO    NO   NO2    NOX    O3   PM10   PM2.5  \
0     2022-01-01 00:00:00  2.22   4.7  25.3   30.0  22.0  273.0  223.32
1     2022-01-01 01:00:00  2.54  12.0  31.3   43.1  12.0  169.0  114.31
2     2022-01-01 02:00:00  4.30  72.0  39.1  110.9   6.0  215.0  143.92
3     2022-01-01 03:00:00  2.07  12.9  17.8   30.6  15.0  291.0  218.59
4     2022-01-01 04:00:00  1.08   3.0   3.8    6.7  24.0  134.0   71.94
...                   ...   ...   ...   ...    ...   ...    ...     ...
14250 2023-08-17 19:00:00  0.30   2.9   8.7   11.6  39.0  109.0     NaN
14251 2023-08-17 20:00:00  0.33   2.9  10.5   13.4  32.0  102.0     NaN
14252 2023-08-17 21:00:00  0.34   3.4  15.9   19.3  25.0   97.0     NaN
14253 2023-08-17 22:00:00  0.43   4.8  23.0   27.8  15.0  103.0     NaN
14254 2023-08-17 23:00:00  0.31   3.3  12.5   15.7  22.0  116.0     NaN

         PRS  RAINF    RH  SO2     SR   TOUT   WSR    WDR
0      694.4    0.0  52.0  2.8  0.000  20.61   8.4  318.0
1      694.1    0.0  57.0  2.9  0.053  18.76   4.4  332.0
2      693.9    0.0  59.0  3.4  0.087  18.35   4.6  241.0
3      693.5    0.0  32.0  3.1  0.048  23.93  13.3  283.0
4      693.4    0.0  15.0  3.0  0.035  28.05  15.0  277.0
...      ...    ...   ...  ...    ...    ...   ...    ...
14250  698.1    0.0  21.0  2.1  0.000  35.28  15.9   87.0
14251  698.4    0.0  22.0  2.0  0.000  34.24  15.8   87.0
14252  698.8    0.0  22.0  2.0  0.000  33.37  14.5   85.0
14253  699.3    0.0  24.0  2.0  0.000  32.70  12.6   87.0
14254  699.7    0.0  37.0  1.9  0.000  31.18  15.7   82.0

[14255 rows x 16 columns]

Here we notice that the database of 2023 and 2024 is not organized by station, so we will do it manually.

In [6]:
print(db_2023_2024['Hoja2']) #it is empty, so we will create a dictionary of dataframes from the data of the first sheet

print(db_2023_2024['Param_horarios_Estaciones'].columns)
df = db_2023_2024['Param_horarios_Estaciones']

df = df.drop(index=0).reset_index(drop=True) 
df = df.drop(index=0).reset_index(drop=True) 
print(df)

Empty DataFrame
Columns: []
Index: []
Index(['Unnamed: 0', 'SURESTE', 'SURESTE.1', 'SURESTE.2', 'SURESTE.3',
       'SURESTE.4', 'SURESTE.5', 'SURESTE.6', 'SURESTE.7', 'SURESTE.8',
       ...
       'NOROESTE 3.5', 'NOROESTE 3.6', 'NOROESTE 3.7', 'NOROESTE 3.8',
       'NOROESTE 3.9', 'NOROESTE 3.10', 'NOROESTE 3.11', 'NOROESTE 3.12',
       'NOROESTE 3.13', 'NOROESTE 3.14'],
      dtype='object', length=240)
                Unnamed: 0 SURESTE SURESTE.1 SURESTE.2 SURESTE.3 SURESTE.4  \
0      2023-01-01 00:00:00    2.37      54.5      32.6      87.1         3
1      2023-01-01 01:00:00    2.12      38.7      30.3      68.9         3
2      2023-01-01 02:00:00    2.05      38.7      28.8      67.4         3
3      2023-01-01 03:00:00     2.5      60.5      29.1      89.4         3
4      2023-01-01 04:00:00    1.94      42.3      25.7      67.7       NaN
...                    ...     ...       ...       ...       ...       ...
13865  2024-07-31 19:00:00    0.67       NaN       4.3       7.5        26
13866  2024-07-31 20:00:00    0.66       2.9       4.5       7.4        24
13867  2024-07-31 21:00:00    0.65       2.7       3.9       6.6        24
13868  2024-07-31 22:00:00    0.65       2.8       3.9       6.7        23
13869  2024-07-31 23:00:00    0.68       2.5       4.8       7.3        20

      SURESTE.5 SURESTE.6 SURESTE.7 SURESTE.8  ... NOROESTE 3.5 NOROESTE 3.6  \
0           110        68     721.7         0  ...          NaN          NaN
1           116     67.18     721.5         0  ...          246          NaN
2           117     75.12     721.1         0  ...          239          NaN
3           135     82.81     720.8         0  ...          275          NaN
4           132     59.56     720.7         0  ...          NaN          NaN
...         ...       ...       ...       ...  ...          ...          ...
13865        88       NaN     721.7         0  ...          117        13.73
13866        94       NaN     721.8         0  ...           90        13.05
13867        83       NaN     722.1         0  ...           90        12.72
13868        95       NaN     722.5         0  ...          104        13.63
13869       103       NaN     723.2         0  ...          NaN          NaN

      NOROESTE 3.7 NOROESTE 3.8 NOROESTE 3.9 NOROESTE 3.10  NOROESTE 3.11  \
0              NaN          NaN          NaN           NaN            NaN
1            707.4            0           59           2.9              0
2              707            0           59           3.2              0
3            706.8            0           59           2.3              0
4            706.8            0           58           1.8              0
...            ...          ...          ...           ...            ...
13865        707.5            0           46           2.8          0.003
13866        707.9            0           48           2.7              0
13867        708.4            0           50             3              0
13868        709.1            0           58             3              0
13869          NaN          NaN          NaN           NaN            NaN

      NOROESTE 3.12 NOROESTE 3.13 NOROESTE 3.14
0               NaN           NaN           NaN
1             14.14          65.3            95
2             14.11          60.9            90
3             14.08          58.1            84
4             12.94          61.4            87
...             ...           ...           ...
13865         29.87          13.1            63
13866         28.93          11.8            41
13867         28.31          11.6            41
13868         27.25          15.3            35
13869           NaN           NaN           NaN

[13870 rows x 240 columns]

In [7]:
import pandas as pd  # Assuming pandas is imported

# Your DataFrame
df = db_2023_2024['Param_horarios_Estaciones']

# Define lists of stations and starting column indices
estaciones_db_2023_2024 = [
    'SURESTE', 'NORESTE', 'CENTRO', 'NOROESTE', 'SUROESTE',
    'NOROESTE2', 'NORTE', 'NORESTE2', 'SURESTE2', 'SUROESTE2',
    'SURESTE 3', 'SUR', 'NORTE2', 'NORESTE3', 'NOROESTE3'
]
estaciones_db_2023_2024_inicio = [1, 17, 33, 49, 65, 81, 97, 113, 129, 145, 161, 177, 193, 209, 225]

# Create the dictionary
diccionario_db_2023_2024 = {}
for estacion, inicio in zip(estaciones_db_2023_2024, estaciones_db_2023_2024_inicio):
    # Select column 0 (date) and 15 parameter columns (inicio to inicio + 14, inclusive)
    cols_indices = [0] + list(range(inicio, inicio + 15))  # Adjusted to 15 to include all parameters
    # Verify that indices don't exceed the number of columns
    print("-"*10,estacion)
    cols = df.iloc[:, cols_indices]
    # Use row 0 as column names (parameters: date, CO, NO, etc.)
    new_column_names = ['date'] + cols.iloc[0, 1:].fillna('unknown').tolist()  # Replace NaN in row 0, skip date column
    # Create new DataFrame, dropping rows 0 (parameters) and 1 (units)
    new_df = cols.drop(index=[0, 1]).reset_index(drop=True).copy()
    # Assign new column names
    new_df.columns = new_column_names
    diccionario_db_2023_2024[estacion] = new_df
    print(diccionario_db_2023_2024[estacion].head())
    
# Example: Print first few rows of NOROESTE3

print("Claves del diccionario:", diccionario_db_2023_2024.keys())

---------- SURESTE
                  date    CO    NO   NO2   NOX   O3 PM10  PM2.5    PRS RAINF  \
0  2023-01-01 00:00:00  2.37  54.5  32.6  87.1    3  110     68  721.7     0
1  2023-01-01 01:00:00  2.12  38.7  30.3  68.9    3  116  67.18  721.5     0
2  2023-01-01 02:00:00  2.05  38.7  28.8  67.4    3  117  75.12  721.1     0
3  2023-01-01 03:00:00   2.5  60.5  29.1  89.4    3  135  82.81  720.8     0
4  2023-01-01 04:00:00  1.94  42.3  25.7  67.7  NaN  132  59.56  720.7     0

   RH  SO2 SR   TOUT  WSR  WDV
0  68  3.5  0  16.39  3.2  257
1  72  3.4  0  15.17  3.3  278
2  71  3.6  0  14.82  3.7  278
3  68  3.8  0  15.51  3.6  197
4  73  3.6  0  13.81  4.9  271
---------- NORESTE
                  date    CO    NO   NO2    NOX O3 PM10 PM2.5    PRS RAINF  \
0  2023-01-01 00:00:00   3.4  30.4    43   73.4  7  222   NaN  718.4     0
1  2023-01-01 01:00:00   4.3  67.2  44.4  111.6  8  311   NaN  718.1     0
2  2023-01-01 02:00:00  4.28  63.9  41.5  105.5  7  723   400  717.8     0
3  2023-01-01 03:00:00  3.77  57.2  42.3   99.5  6  473   349  717.6     0
4  2023-01-01 04:00:00  2.98  41.9  39.9   81.8  5  372   260  717.6     0

   RH  SO2 SR   TOUT  WSR  WDV
0  61  3.8  0  19.01  4.1  190
1  61   24  0  17.32  1.4  222
2  69  9.8  0  16.22  2.5    4
3  72  7.8  0  15.57  1.6  330
4  72  7.3  0  15.53  4.1  343
---------- CENTRO
                  date    CO   NO   NO2   NOX  O3 PM10  PM2.5    PRS RAINF  \
0  2023-01-01 00:00:00  1.67  4.1  30.3  34.5   9  118  94.12  718.4     0
1  2023-01-01 01:00:00   1.7    5  28.9  34.1   9   97  96.79  710.7     0
2  2023-01-01 02:00:00  1.51  4.3  23.2  27.7  11  103  81.23  710.4     0
3  2023-01-01 03:00:00   1.3  3.8  20.9  24.9  11   83  49.83  710.1     0
4  2023-01-01 04:00:00  1.28  4.6  20.7  25.5   9   65  40.19  710.2     0

   RH  SO2     SR   TOUT  WSR  WDV
0  45  3.3      0  17.65  4.9  236
1  47  3.4  0.001  17.12  3.4  336
2  46  3.4  0.001  16.69  3.4    3
3  48  3.2  0.001  15.99  2.6  315
4  55    3  0.001  14.74  3.9  270
---------- NOROESTE
                  date    CO    NO   NO2    NOX O3 PM10 PM2.5    PRS RAINF  \
0  2023-01-01 00:00:00  4.37  60.5  46.8  107.3  5  426   421  711.8     0
1  2023-01-01 01:00:00  2.88  30.1  42.1   72.2  4  393   362  711.5     0
2  2023-01-01 02:00:00  2.97  33.5  40.8   74.3  4  372   312  711.1     0
3  2023-01-01 03:00:00  3.15  47.6  38.5   86.1  4  260   222  710.9     0
4  2023-01-01 04:00:00  2.24  24.5  34.1   58.6  3  189   143  710.9     0

   RH   SO2 SR   TOUT  WSR  WDV
0  58   5.6  0  18.37  5.5  327
1  59  12.8  0  17.93  7.2  322
2  60   9.4  0  17.08  6.4  316
3  63   6.1  0  16.24  6.1  327
4  62   5.6  0  16.03  6.9  326
---------- SUROESTE
                  date    CO    NO   NO2    NOX O3 PM10 PM2.5    PRS RAINF  \
0  2023-01-01 00:00:00  3.67  53.1  40.6   93.6  8  221   NaN  701.2     0
1  2023-01-01 01:00:00   3.9  64.7    38  102.7  8  267   NaN  700.9     0
2  2023-01-01 02:00:00  4.28  77.7  35.7  113.4  8  320   NaN  700.6     0
3  2023-01-01 03:00:00  3.15    57  34.6   91.6  6  361   129  700.1     0
4  2023-01-01 04:00:00  2.32  26.9  31.8   58.7  6  166    74  700.1     0

   RH  SO2 SR   TOUT  WSR  WDV
0  55  4.4  0  15.66  2.9  307
1  58  4.9  0  15.04  2.2  310
2  58  5.5  0  15.13  2.7  270
3  55  5.2  0  15.33  3.2  271
4  52  5.1  0  15.53  2.5  260
---------- NOROESTE2
                  date    CO    NO   NO2   NOX  O3 PM10   PM2.5    PRS RAINF  \
0  2023-01-01 00:00:00  2.07  31.6  40.6    72   7  398   221.6  700.3     0
1  2023-01-01 01:00:00  2.09  11.3  30.1  41.3   5  265  114.16  699.9     0
2  2023-01-01 02:00:00  2.17  39.4  31.7  70.9   5  167   84.92  699.4     0
3  2023-01-01 03:00:00  2.21  13.6    27  40.5   6  133   63.62  699.2     0
4  2023-01-01 04:00:00  2.15   6.1  16.4  22.5  10   86   29.06  699.2     0

   RH  SO2   SR   TOUT   WSR  WDV
0  53  2.1  NaN  15.93   4.6  306
1  53    2  NaN  14.96   6.2  298
2  54  2.1  NaN  14.51   3.4  295
3  55  2.1  NaN  14.23   7.1  305
4  52  2.2  NaN  14.23  12.3  303
---------- NORTE
                  date    CO     NO   NO2    NOX  O3 PM10   PM2.5    PRS  \
0  2023-01-01 00:00:00  7.46  130.4  43.2  173.5  12  522  369.16  715.7
1  2023-01-01 01:00:00  4.16   56.2  41.1   97.2   9  712  299.29  715.5
2  2023-01-01 02:00:00  3.19   42.4  37.9   80.2   7  586  201.58  715.1
3  2023-01-01 03:00:00   3.1   46.1  34.9   80.9   7  406  186.32  714.9
4  2023-01-01 04:00:00   3.2   59.2  33.5   92.7   7  340   168.5  714.9

  RAINF   RH  SO2 SR   TOUT  WSR WDV
0     0  NaN  4.2  0  17.05  3.8  18
1     0  NaN    4  0  15.87  4.5  15
2     0  NaN  3.8  0  15.41  4.8  28
3     0  NaN  3.7  0  14.58  2.8  26
4     0  NaN  3.8  0  13.84  4.1  28
---------- NORESTE2
                  date    CO    NO   NO2   NOX  O3 PM10 PM2.5    PRS RAINF  \
0  2023-01-01 00:00:00  2.12  10.2  34.1  44.3  12   93    67  714.1     0
1  2023-01-01 01:00:00  1.97   6.7  34.3  40.9  10  162   101  713.8     0
2  2023-01-01 02:00:00  2.21  17.6  34.1  51.7   8  209   143  713.4     0
3  2023-01-01 03:00:00  2.41  34.9  32.3  67.3   8  220   154    713     0
4  2023-01-01 04:00:00  2.57  47.9    34  81.9   8  219   166    713     0

   RH  SO2     SR   TOUT   WSR  WDV
0  57  3.1      0  20.21    14  316
1  62  3.8      0  18.19   7.3  259
2  68  3.7      0  16.41    10  126
3  73  3.6  0.019  16.42  13.1   90
4  73  3.5      0  15.03  14.6  139
---------- SURESTE2
                  date    CO     NO   NO2    NOX  O3 PM10 PM2.5    PRS RAINF  \
0  2023-01-01 00:00:00  2.91   36.6  33.6   70.2  10  100   NaN  714.1     0
1  2023-01-01 01:00:00   4.8   94.3  32.7    127  13  198   NaN    722     0
2  2023-01-01 02:00:00  6.58    144  29.6  173.6  13  436   NaN  721.9     0
3  2023-01-01 03:00:00  6.95  173.2  27.4  200.6  11  558   NaN  721.7     0
4  2023-01-01 04:00:00  6.77  151.7  23.6  175.3  12  551   NaN  721.7     0

   RH  SO2 SR   TOUT  WSR  WDR
0  57    3  0  18.64  1.4   55
1  68  3.9  0  17.34  0.5   14
2  70    5  0   16.6  1.3  227
3  73  5.1  0  15.81  1.4  237
4  75  4.7  0     15  1.4  234
---------- SUROESTE2
                  date    CO   NO   NO2   NOX  O3 PM10 PM2.5    PRS RAINF  RH  \
0  2023-01-01 00:00:00  1.14  3.9  15.8  19.6  17   64    34  713.5     0  45
1  2023-01-01 01:00:00  1.04  3.8    13  16.8  19   71    30  713.5     0  46
2  2023-01-01 02:00:00  1.03  5.2  15.5  20.6  16   85    32  713.3     0  47
3  2023-01-01 03:00:00  1.03  3.9  15.9  19.8  16   57    30  713.1     0  44
4  2023-01-01 04:00:00  0.85  3.8  11.3  15.1  19   59    20  713.1     0  44

   SO2 SR   TOUT  WSR  WDR
0  3.9  0  16.96  5.5  250
1  3.8  0  16.78  4.9  248
2  3.8  0  16.22  4.6  236
3  3.8  0  16.99    5  229
4  3.7  0  16.74  5.5  203
---------- SURESTE 3
                  date    CO    NO   NO2   NOX O3 PM10 PM2.5    PRS RAINF  RH  \
0  2023-01-01 00:00:00  3.08  13.8  30.9  44.7  5  206   144  731.1     0  64
1  2023-01-01 01:00:00  2.34    16  23.3  39.1  7  293   190  730.7     0  67
2  2023-01-01 02:00:00  1.82   6.1  17.5  23.3  8  257    93  730.6     0  72
3  2023-01-01 03:00:00  2.52  23.6  24.2  47.6  4   89    85  730.3     0  77
4  2023-01-01 04:00:00  3.25  35.7  23.1  58.7  4  204   145  730.2     0  80

   SO2     SR   TOUT  WSR  WDR
0  5.8      0  18.22  3.2  354
1  6.9  0.001  17.13  4.7  359
2  5.2  0.001  15.68  4.3  313
3  4.5  0.001  14.23    4  303
4  4.2  0.001  13.36  5.2  291
---------- SUR
                  date    CO   NO    NO2    NOX O3 PM10 PM2.5    PRS RAINF  \
0  2023-01-01 00:00:00  2.04  7.2  136.1  143.3  6   56    36  712.1     0
1  2023-01-01 01:00:00  2.01  8.3  107.9    116  6   82    51  711.9     0
2  2023-01-01 02:00:00  1.89  9.2    136  144.9  6   90    57  711.5     0
3  2023-01-01 03:00:00   1.7  7.3   96.5  103.5  7   76    39  711.2     0
4  2023-01-01 04:00:00  1.66    6  122.2    128  6   45    20  711.1     0

   RH  SO2     SR   TOUT  WSR  WDR
0  64  2.4      0  15.05  1.2  251
1  69  2.5  0.001  14.23  2.2  275
2  73  2.5  0.001   13.5  2.1  235
3  70  2.5  0.001  13.23  3.2  181
4  71  2.5  0.001  12.38  2.6  257
---------- NORTE2
                  date    CO    NO   NO2    NOX  O3 PM10 PM2.5    PRS RAINF  \
0  2023-01-01 00:00:00  4.48    73  49.8  122.9  14  228   188  712.1     0
1  2023-01-01 01:00:00  4.86  64.7  47.3    112  13  478   341  711.8     0
2  2023-01-01 02:00:00  3.77  44.9  43.1     88  11  566   352  711.5     0
3  2023-01-01 03:00:00  3.71  63.7  42.1  105.9  11  498   290  711.2     0
4  2023-01-01 04:00:00  4.36  91.7  40.4  132.3  11  483   308  711.2     0

   RH  SO2 SR   TOUT  WSR  WDR
0  54  4.5  0  18.16  5.5  221
1  58  5.8  0  17.84  2.2  272
2  62    6  0  16.87  3.7  221
3  60  6.1  0  16.61  2.5  290
4  67    5  0  15.24  1.9  280
---------- NORESTE3
                  date     CO    NO   NO2   NOX   O3 PM10 PM2.5  PRS RAINF  \
0  2023-01-01 00:00:00  0.832  12.7  14.9  26.4  5.9   73   NaN  729     0
1  2023-01-01 01:00:00  1.319  19.1  18.1  36.4  4.9   92   NaN  729     0
2  2023-01-01 02:00:00  1.161  19.2  17.2  35.6  4.7  133   NaN  729     0
3  2023-01-01 03:00:00  1.083  20.7    17  36.9  4.4  115   NaN  728     0
4  2023-01-01 04:00:00  1.092  19.2  18.1  36.5  4.7  114   NaN  728     0

   RH  SO2   SR  TOUT  WSR  WDR
0  77  2.7    0  14.4  0.5  305
1  79  2.8  NaN  13.4  3.6  254
2  84  2.8  NaN  12.2  4.1  250
3  86  2.9  NaN  11.2  4.4  246
4  86  2.9  NaN  11.5  5.1  264
---------- NOROESTE3
                  date    CO    NO   NO2   NOX   O3 PM10 PM2.5    PRS RAINF  \
0  2023-01-01 00:00:00   NaN   NaN   NaN   NaN  NaN  NaN   NaN    NaN   NaN
1  2023-01-01 01:00:00  2.42  14.7  28.8  43.5    3  246   NaN  707.4     0
2  2023-01-01 02:00:00  2.31  18.5  26.8  45.3    3  239   NaN    707     0
3  2023-01-01 03:00:00  1.78  15.5    24  39.5    2  275   NaN  706.8     0
4  2023-01-01 04:00:00  1.56  10.5  22.2  32.7    2  NaN   NaN  706.8     0

    RH  SO2   SR   TOUT   WSR  WDR
0  NaN  NaN  NaN    NaN   NaN  NaN
1   59  2.9    0  14.14  65.3   95
2   59  3.2    0  14.11  60.9   90
3   59  2.3    0  14.08  58.1   84
4   58  1.8    0  12.94  61.4   87
Claves del diccionario: dict_keys(['SURESTE', 'NORESTE', 'CENTRO', 'NOROESTE', 'SUROESTE', 'NOROESTE2', 'NORTE', 'NORESTE2', 'SURESTE2', 'SUROESTE2', 'SURESTE 3', 'SUR', 'NORTE2', 'NORESTE3', 'NOROESTE3'])

Now I will rewrite the dictionary that we imported from the beggining.

In [8]:
db_2023_2024 = diccionario_db_2023_2024
print(db_2023_2024.keys())

with pd.ExcelWriter('Bases_Datos/DATOS HISTÓRICOS 2023_2024_TODAS ESTACIONES - corregido.xlsx', engine='openpyxl') as writer:
    for sheet_name, df in db_2023_2024.items():
        df.to_excel(writer, sheet_name=sheet_name, index=False)

print("Archivo Excel creado DATOS HISTÓRICOS 2023_2024_TODAS ESTACIONES - corregido.xlsx")

dict_keys(['SURESTE', 'NORESTE', 'CENTRO', 'NOROESTE', 'SUROESTE', 'NOROESTE2', 'NORTE', 'NORESTE2', 'SURESTE2', 'SUROESTE2', 'SURESTE 3', 'SUR', 'NORTE2', 'NORESTE3', 'NOROESTE3'])
Archivo Excel creado DATOS HISTÓRICOS 2023_2024_TODAS ESTACIONES - corregido.xlsx

Since 2023 is repeated in 2 datasets, the data is repeated. Thus, records for 2023 in the dictionary db_2022_2023 will be removed. The reason of this selection is because in the database 2022-2023 information of year 2023 from august to december doesn't exist.

In [9]:
# db_2022_2023
db_2022={}

for estacion in db_2022_2023.keys():
    df = db_2022_2023[estacion]
    #we are filtering the df, so then it doesn´t include the records in which year is 2023
    df_filtrado = df[~df.iloc[:, 0].astype(str).str.contains("2023", na=False)]

    db_2022[estacion] = df_filtrado

    print("-"*30,estacion)
    print(df_filtrado.tail(5))

------------------------------ SURESTE
                    date    CO    NO   NO2   NOX    O3   PM10  PM2.5    PRS  \
8755 2022-12-31 19:00:00  1.51  12.1  39.9  51.9  10.0   52.0  23.08  721.1
8756 2022-12-31 20:00:00  1.93  28.7  41.1  69.7   6.0   60.0  38.44  721.4
8757 2022-12-31 21:00:00  2.47  56.3  43.0  99.1   5.0   86.0  62.71  721.5
8758 2022-12-31 22:00:00  2.45  52.8  39.2  91.8   4.0  135.0  72.58  721.7
8759 2022-12-31 23:00:00  2.23  27.5  34.2  61.6   4.0  127.0  72.58  722.0

      RAINF    RH  SO2   SR   TOUT  WSR    WDR
8755    0.0  47.0  3.4  0.0  21.64  5.5  198.0
8756    0.0  51.0  3.4  0.0  20.25  4.6  227.0
8757    0.0  56.0  3.5  0.0  19.07  4.8  240.0
8758    0.0  56.0  3.5  0.0  18.63  4.3  249.0
8759    0.0  61.0  3.3  0.0  17.74  4.4  214.0
------------------------------ NORESTE
                    date    CO    NO   NO2    NOX    O3   PM10  PM2.5    PRS  \
8755 2022-12-31 19:00:00  1.77  16.0  44.5   60.5  12.0   84.0   52.0  717.7
8756 2022-12-31 20:00:00  3.43  54.8  57.9  112.7   8.0  142.0    NaN  717.9
8757 2022-12-31 21:00:00  3.78  52.0  54.9  106.9   8.0  275.0    NaN  718.1
8758 2022-12-31 22:00:00  2.20   7.8  29.7   37.5  13.0  280.0  158.0  718.3
8759 2022-12-31 23:00:00  2.28   8.2  30.9   39.2  13.0  191.0  177.0  718.5

      RAINF    RH  SO2   SR   TOUT  WSR    WDR
8755    0.0  43.0  5.0  0.0  22.98  4.7  123.0
8756    0.0  48.0  4.6  0.0  21.69  3.1  171.0
8757    0.0  52.0  3.9  0.0  21.56  5.2  161.0
8758    0.0  57.0  3.0  0.0  21.43  8.7  155.0
8759    0.0  60.0  3.0  0.0  20.47  5.9  176.0
------------------------------ CENTRO
                    date    CO    NO   NO2   NOX    O3  PM10  PM2.5    PRS  \
8755 2022-12-31 19:00:00  1.22   3.3  23.4  26.9  26.0  48.0  17.71  710.3
8756 2022-12-31 20:00:00  1.32   3.6  26.5  30.3  18.0  46.0  23.32  710.6
8757 2022-12-31 21:00:00  1.61  13.2  38.3  51.7   7.0  55.0  34.85  710.7
8758 2022-12-31 22:00:00  1.90  15.6  41.1  56.9   5.0  73.0  55.44  710.9
8759 2022-12-31 23:00:00  1.85   9.0  37.6  46.8   7.0  87.0    NaN  711.1

      RAINF    RH  SO2     SR   TOUT  WSR    WDR
8755    0.0  40.0  3.4  0.001  21.60  3.9   28.0
8756    0.0  44.0  NaN  0.001  19.98  3.6  273.0
8757    0.0  47.0  NaN  0.001  18.98  3.7  238.0
8758    0.0  47.0  3.5  0.001  18.28  3.9  237.0
8759    0.0  45.0  3.5  0.001  18.25  6.7  219.0
------------------------------ NOROESTE
                    date    CO     NO   NO2    NOX    O3   PM10  PM2.5    PRS  \
8755 2022-12-31 19:00:00  1.44    4.4  31.3   35.7  18.0   48.0   39.0  711.1
8756 2022-12-31 20:00:00  2.69   31.6  50.4   82.0   8.0   84.0   79.0  711.3
8757 2022-12-31 21:00:00  5.81  111.3  65.0  176.2  10.0  267.0  227.0  711.6
8758 2022-12-31 22:00:00  5.79   97.2  61.9  159.1   8.0  390.0  358.0  711.8
8759 2022-12-31 23:00:00  5.83   85.6  58.6  144.2   8.0  452.0  442.0  711.9

      RAINF    RH  SO2   SR   TOUT  WSR    WDR
8755    0.0  36.0  5.5  0.0  23.49  6.4   98.0
8756    0.0  41.0  6.2  0.0  22.28  3.1  128.0
8757    0.0  46.0  6.6  0.0  20.87  4.6  272.0
8758    0.0  48.0  6.2  0.0  20.32  4.5  279.0
8759    0.0  51.0  6.3  0.0  19.51  6.0  312.0
------------------------------ SUROESTE
                    date    CO    NO   NO2    NOX    O3   PM10  PM2.5    PRS  \
8755 2022-12-31 19:00:00  1.65   7.5  34.3   41.8  21.0   57.0   48.0  700.3
8756 2022-12-31 20:00:00  2.04  19.7  37.4   57.1  16.0   82.0   60.0  700.6
8757 2022-12-31 21:00:00  3.02  65.7  47.8  113.4   8.0  108.0    NaN  700.9
8758 2022-12-31 22:00:00  3.72  85.6  45.9  131.4   9.0  197.0    NaN  701.1
8759 2022-12-31 23:00:00  3.46  48.4  41.8   90.2   8.0  266.0  224.0  701.3

      RAINF    RH  SO2   SR   TOUT  WSR    WDR
8755    0.0  40.0  5.2  0.0  22.03  4.6  185.0
8756    0.0  43.0  4.6  0.0  20.70  1.8  160.0
8757    0.0  47.0  4.6  0.0  18.32  2.9  321.0
8758    0.0  49.0  4.8  0.0  17.23  3.3  307.0
8759    0.0  52.0  4.2  0.0  16.35  2.8  316.0
------------------------------ NOROESTE2
                    date    CO     NO   NO2    NOX    O3   PM10   PM2.5  \
8755 2022-12-31 19:00:00  1.96   10.3  37.3   47.5  22.0   69.0   43.54
8756 2022-12-31 20:00:00  1.92   19.8  55.7   75.3   7.0   97.0     NaN
8757 2022-12-31 21:00:00  2.00  101.0  58.5  159.3   6.0  162.0  140.15
8758 2022-12-31 22:00:00  2.03   75.3  53.4  128.5   6.0  203.0     NaN
8759 2022-12-31 23:00:00  2.04   50.1  53.9  103.7   9.0  258.0     NaN

        PRS  RAINF    RH  SO2     SR   TOUT  WSR    WDR
8755  699.4    0.0  40.0  2.8  0.422  21.78  6.8   84.0
8756  699.8    0.0  45.0  2.5  0.559  20.11  2.3  132.0
8757  700.0    0.0  47.0  3.0  0.885  19.12  2.9  225.0
8758  700.2    0.0  49.0  2.7  0.820  17.83  2.9  359.0
8759  700.4    0.0  51.0  2.4  0.696  17.20  4.3  303.0
------------------------------ NORTE
                    date    CO     NO   NO2    NOX    O3   PM10   PM2.5  \
8755 2022-12-31 19:00:00  1.75   28.4  45.6   73.9  11.0   70.0   34.63
8756 2022-12-31 20:00:00  3.45   81.9  50.8  132.5   8.0  138.0   84.04
8757 2022-12-31 21:00:00  5.49  131.9  54.0  185.7  12.0  259.0  224.50
8758 2022-12-31 22:00:00  7.42  138.5  53.6  192.0  16.0  504.0  384.02
8759 2022-12-31 23:00:00  6.17   84.2  47.8  131.9  10.0  705.0  267.68

        PRS  RAINF    RH  SO2   SR   TOUT  WSR   WDR
8755  714.9    0.0  72.0  3.8  0.0  21.86  3.7  31.0
8756  715.3    0.0  70.0  4.0  0.0  20.07  2.4  33.0
8757  715.5    0.0  69.0  4.1  0.0  19.13  2.3  32.0
8758  715.7    0.0  69.0  4.4  0.0  18.81  2.7  19.0
8759  715.8    0.0  69.0  3.7  0.0  18.82  3.1  27.0
------------------------------ SUROESTE2
                    date    CO   NO   NO2   NOX    O3   PM10  PM2.5    PRS  \
8755 2022-12-31 19:00:00  0.94  4.5  17.0  21.5  25.0   46.0   19.0  713.2
8756 2022-12-31 20:00:00  1.11  7.9  22.6  30.5  20.0   47.0   13.0  713.4
8757 2022-12-31 21:00:00  1.57  6.9  27.1  34.1  14.0   59.0   32.0  713.4
8758 2022-12-31 22:00:00  1.68  9.2  34.8  44.0   8.0   83.0   54.0  713.6
8759 2022-12-31 23:00:00  1.18  4.2  16.6  20.9  18.0  122.0   53.0  713.7

      RAINF    RH  SO2   SR   TOUT  WSR    WDR
8755    0.0  40.0  4.5  0.0  20.95  8.7  153.0
8756    0.0  42.0  4.1  0.0  19.76  6.4  181.0
8757    0.0  45.0  4.0  0.0  18.78  4.1  249.0
8758    0.0  45.0  4.0  0.0  18.01  6.5  251.0
8759    0.0  43.0  4.0  0.0  17.51  6.5  240.0
------------------------------ SURESTE2
                    date    CO     NO   NO2    NOX    O3   PM10  PM2.5    PRS  \
8755 2022-12-31 19:00:00  3.92  109.9  51.0  160.9  10.0   65.0    NaN  721.8
8756 2022-12-31 20:00:00  5.99  213.9  49.6  263.5  12.0  236.0    NaN  721.9
8757 2022-12-31 21:00:00  2.72   48.2  38.7   86.9   9.0  433.0    NaN  722.1
8758 2022-12-31 22:00:00  1.85   11.6  27.9   39.5  14.0  168.0    NaN  722.1
8759 2022-12-31 23:00:00  1.88   12.2  29.5   41.7  13.0  119.0    NaN  722.2

      RAINF    RH  SO2   SR   TOUT  WSR    WDR
8755    0.0  39.0  4.0  0.0  23.82  1.1  151.0
8756    0.0  47.0  5.2  0.0  21.94  1.4  165.0
8757    0.0  53.0  3.5  0.0  20.74  1.4  131.0
8758    0.0  57.0  3.0  0.0  20.63  1.5  126.0
8759    0.0  58.0  2.9  0.0  20.14  1.3  125.0
------------------------------ SURESTE3
                    date    CO    NO   NO2   NOX   O3   PM10  PM2.5    PRS  \
8755 2022-12-31 19:00:00  2.70  32.4  45.2  77.4  7.0  116.0   50.0  730.1
8756 2022-12-31 20:00:00  3.04  39.2  40.5  79.5  7.0  250.0   85.0  730.6
8757 2022-12-31 21:00:00  2.62  19.3  37.2  56.3  5.0  300.0  115.0  730.9
8758 2022-12-31 22:00:00  3.19  51.9  36.0  87.8  5.0  238.0  111.0  731.1
8759 2022-12-31 23:00:00  2.56  17.2  31.0  48.0  5.0  278.0  120.0  731.2

      RAINF    RH  SO2     SR   TOUT  WSR    WDR
8755    0.0  43.0  4.3  0.002  24.53  4.5  132.0
8756    0.0  52.0  4.1  0.001  22.23  4.5  155.0
8757    0.0  58.0  4.1  0.001  20.25  4.8  152.0
8758    0.0  62.0  5.2  0.001  18.86  2.4  216.0
8759    0.0  64.0  4.7  0.001  18.05  3.0  275.0
------------------------------ SUR
                    date    CO   NO   NO2   NOX    O3  PM10  PM2.5    PRS  \
8755 2022-12-31 19:00:00  1.66  5.2  39.6  44.6  15.0  34.0   10.0  711.3
8756 2022-12-31 20:00:00  1.62  5.0  24.3  29.1  16.0  47.0   15.0  711.6
8757 2022-12-31 21:00:00  1.76  5.1  48.4  53.3  13.0  45.0   19.0  711.7
8758 2022-12-31 22:00:00  1.77  4.5  48.4  52.8  14.0  64.0   40.0  712.0
8759 2022-12-31 23:00:00  1.70  5.8  75.9  81.6  11.0  65.0   29.0  712.2

      RAINF    RH  SO2     SR   TOUT  WSR    WDR
8755    0.0  43.0  2.4  0.001  21.34  5.3  149.0
8756    0.0  47.0  2.4  0.001  19.29  7.0  141.0
8757    0.0  50.0  2.3  0.001  18.40  5.2  107.0
8758    0.0  52.0  2.4  0.001  18.22  5.1  131.0
8759    0.0  57.0  2.1  0.001  16.66  3.6  222.0
------------------------------ NORTE2
                    date    CO    NO   NO2    NOX    O3   PM10  PM2.5    PRS  \
8755 2022-12-31 19:00:00  1.17   8.3  31.2   39.5  25.0   46.0   16.0  711.4
8756 2022-12-31 20:00:00  1.23   8.1  36.2   44.3  18.0   66.0   12.0  711.6
8757 2022-12-31 21:00:00  2.13  79.6  48.6  128.3  11.0   65.0   10.0  711.8
8758 2022-12-31 22:00:00  1.47   8.7  34.8   43.4  16.0  128.0   34.0  712.0
8759 2022-12-31 23:00:00  2.58  39.8  44.9   84.7  11.0  103.0   67.0  712.2

      RAINF    RH  SO2   SR   TOUT  WSR    WDR
8755    0.0  38.0  3.5  0.0  23.37  3.4  113.0
8756    0.0  43.0  5.4  0.0  21.45  1.1  218.0
8757    0.0  46.0  6.8  0.0  20.84  2.8   29.0
8758    0.0  51.0  3.9  0.0  21.30  1.3  130.0
8759    0.0  56.0  3.9  0.0  19.29  0.9  169.0
------------------------------ NORESTE2
                    date    CO    NO   NO2   NOX    O3   PM10  PM2.5    PRS  \
8755 2022-12-31 19:00:00  1.38  35.6  53.6  89.2  11.0   72.0   19.0  713.1
8756 2022-12-31 20:00:00   NaN   NaN   NaN   NaN   NaN    NaN    NaN    NaN
8757 2022-12-31 21:00:00  1.88  47.8  52.0  99.8   8.0  152.0   88.0  713.7
8758 2022-12-31 22:00:00  2.32  25.3  44.5  69.9  10.0  188.0  107.0  714.0
8759 2022-12-31 23:00:00  2.39   5.5  23.5  29.0  19.0  166.0   67.0  714.2

      RAINF    RH   SO2     SR   TOUT   WSR    WDR
8755    0.0  36.0  23.1  0.029  25.39  11.6  276.0
8756    NaN   NaN   NaN  0.000    NaN   NaN    NaN
8757    0.0  45.0   6.1  0.038  23.66  15.5  331.0
8758    0.0  51.0   3.6  0.012  21.84  15.1  328.0
8759    0.0  54.0   2.8  0.015  21.53  15.7  331.0
------------------------------ NORESTE3
                    date     CO    NO   NO2   NOX    O3  PM10  PM2.5    PRS  \
8755 2022-12-31 19:00:00  0.623  10.4  15.6  25.1  27.3  28.0    NaN  728.0
8756 2022-12-31 20:00:00  0.539   8.0  14.5  21.7  15.9  48.0    NaN  729.0
8757 2022-12-31 21:00:00  0.483   9.2  11.2  19.6  21.7  60.0    NaN  729.0
8758 2022-12-31 22:00:00  0.706  18.4  14.7  32.2  12.2  45.0    NaN  729.0
8759 2022-12-31 23:00:00  0.795  22.8  16.5  38.4   7.0  50.0    NaN  729.0

      RAINF    RH   SO2     SR  TOUT  WSR    WDR
8755    0.0  43.0  10.7  0.001  22.5  1.1  358.0
8756    0.0  55.0   5.0  0.000  19.2  1.6  107.0
8757    0.0  59.0   3.5  0.000  18.1  2.6  120.0
8758    0.0  65.0   3.3  0.000  17.1  2.0  278.0
8759    0.0  72.0   3.0  0.000  15.5  2.4  264.0
------------------------------ NOROESTE3
                   date    CO    NO   NO2   NOX    O3   PM10  PM2.5    PRS  \
738 2022-12-31 19:00:00  1.17   5.1  30.6  35.6  21.0   53.0    NaN  707.0
739 2022-12-31 20:00:00  2.29  55.6  35.6  91.2   8.0   76.0    NaN  707.3
740 2022-12-31 21:00:00  1.79  31.8  32.7  64.5   3.0  110.0    NaN  707.5
741 2022-12-31 22:00:00  3.12  44.0  34.7  78.7   5.0  105.0    NaN  707.8
742 2022-12-31 23:00:00  2.66  35.3  32.4  67.7   4.0  247.0    NaN  707.9

     RAINF    RH  SO2   SR   TOUT   WSR    WDR
738    0.0  63.0  2.1  0.0  21.69  19.1   29.0
739    0.0  62.0  2.5  0.0  19.89  44.5   75.0
740    0.0  61.0  2.0  0.0  17.49  58.8   96.0
741    0.0  60.0  2.5  0.0  17.03  66.0  106.0
742    0.0  60.0  2.2  0.0  15.64  61.3   97.0
------------------------------ CATÁLOGO
            Nombre_Estacion     Clave_Estacion               location
10         Sureste 2 Juarez             Juarez   25.64611,-100.095555
11  Suroeste Santa Catarina     Santa Catarina  25.675356,-100.460037
12           Norte Escobedo           Escobedo   25.80194,-100.343056
13        Noreste 2 Apodaca            Apodaca   25.77722,-100.188055
14           Sureste Tec NL  Tec de Nuevo León   25.66827,-100.249580

In [10]:
#now we will create 2 master datasests

#2020-2022 (joining 2 datasets)

print(db_2020_2021.keys())
print(db_2022.keys())
#verify if the columns are the same, I'll join them 

import pandas as pd

# I'll create a master db containing 2020 and 2022 data
db_2020_2022 = {}

for station in db_2020_2021.keys():
    if station in db_2022:
        df1 = db_2020_2021[station]
        df2 = db_2022[station]
        
        #if the content is the same they will join
        cols1 = df1.columns.tolist()
        cols2 = df2.columns.tolist()
        if cols1 == cols2:
            df_combined = pd.concat([df1, df2], ignore_index=True)
            db_2020_2022[station] = df_combined
        else:
            #I'll say wheter or not they have differences
            print(f"Advertencia: Las columnas de {station} no coinciden.")
            print(f"db_2020_2021[{station}]: {cols1}")
            print(f"db_2022_2023[{station}]: {cols2}")
            #I joing common columns
            common_cols = list(set(cols1).intersection(cols2))
            if common_cols:
                print(f"Usando columnas comunes para {station}: {common_cols}")
                df_combined = pd.concat([df1[common_cols], df2[common_cols]], ignore_index=True)
                df_combined['date'] = pd.to_datetime(df_combined['date'], errors='coerce')
                df_combined = df_combined.sort_values('date').reset_index(drop=True)
                db_2020_2022[station] = df_combined
            elif station=="NOROESTE3":#esta es excepción porque comenzó apartir de 2022 por tanto no estará en la otra db
                    df_combined = df2
                    db_2020_2022[station] = df_combined
                    print("Caso de ",station," exceptúa base de datos 2020-2021 por excepción en Estación Misión San Juan.")
            else:
                print(f"No hay columnas comunes para {station}. Omitiendo.")
    else:
        print(f"Advertencia: La estación {station} no está en db_2022_2023")

# I'll just take 1 CATALOGO
if 'CATÁLOGO' in db_2020_2021:
    db_2020_2022['CATÁLOGO'] = db_2020_2021['CATÁLOGO']  # O usa db_2022_2023['CATÁLOGO']

# I'll check if the keys are the stations
print("Claves de db_2020_2022:", db_2020_2022.keys())

#2023-2024 (already created and separated by station)
db_2023_2024

dict_keys(['SURESTE', 'NORESTE', 'CENTRO', 'NOROESTE', 'SUROESTE', 'NOROESTE2', 'NORTE', 'SUROESTE2', 'SURESTE2', 'SURESTE3', 'SUR', 'NORTE2', 'NORESTE2', 'NORESTE3', 'NOROESTE3', 'CATÁLOGO'])
dict_keys(['SURESTE', 'NORESTE', 'CENTRO', 'NOROESTE', 'SUROESTE', 'NOROESTE2', 'NORTE', 'SUROESTE2', 'SURESTE2', 'SURESTE3', 'SUR', 'NORTE2', 'NORESTE2', 'NORESTE3', 'NOROESTE3', 'CATÁLOGO'])
Advertencia: Las columnas de NOROESTE3 no coinciden.
db_2020_2021[NOROESTE3]: ['NOTA:Estación Misión San Juan inicio operaciones hasta diciembre de 2022']
db_2022_2023[NOROESTE3]: ['date', 'CO', 'NO', 'NO2', 'NOX', 'O3', 'PM10', 'PM2.5', 'PRS', 'RAINF', 'RH', 'SO2', 'SR', 'TOUT', 'WSR', 'WDR']
Caso de  NOROESTE3  exceptúa base de datos 2020-2021 por excepción en Estación Misión San Juan.
Claves de db_2020_2022: dict_keys(['SURESTE', 'NORESTE', 'CENTRO', 'NOROESTE', 'SUROESTE', 'NOROESTE2', 'NORTE', 'SUROESTE2', 'SURESTE2', 'SURESTE3', 'SUR', 'NORTE2', 'NORESTE2', 'NORESTE3', 'NOROESTE3', 'CATÁLOGO'])

{'SURESTE':                       date    CO    NO   NO2   NOX   O3 PM10  PM2.5    PRS  \
 0      2023-01-01 00:00:00  2.37  54.5  32.6  87.1    3  110     68  721.7
 1      2023-01-01 01:00:00  2.12  38.7  30.3  68.9    3  116  67.18  721.5
 2      2023-01-01 02:00:00  2.05  38.7  28.8  67.4    3  117  75.12  721.1
 3      2023-01-01 03:00:00   2.5  60.5  29.1  89.4    3  135  82.81  720.8
 4      2023-01-01 04:00:00  1.94  42.3  25.7  67.7  NaN  132  59.56  720.7
 ...                    ...   ...   ...   ...   ...  ...  ...    ...    ...
 13865  2024-07-31 19:00:00  0.67   NaN   4.3   7.5   26   88    NaN  721.7
 13866  2024-07-31 20:00:00  0.66   2.9   4.5   7.4   24   94    NaN  721.8
 13867  2024-07-31 21:00:00  0.65   2.7   3.9   6.6   24   83    NaN  722.1
 13868  2024-07-31 22:00:00  0.65   2.8   3.9   6.7   23   95    NaN  722.5
 13869  2024-07-31 23:00:00  0.68   2.5   4.8   7.3   20  103    NaN  723.2

       RAINF  RH  SO2     SR   TOUT   WSR  WDV
 0         0  68  3.5      0  16.39   3.2  257
 1         0  72  3.4      0  15.17   3.3  278
 2         0  71  3.6      0  14.82   3.7  278
 3         0  68  3.8      0  15.51   3.6  197
 4         0  73  3.6      0  13.81   4.9  271
 ...     ...  ..  ...    ...    ...   ...  ...
 13865     0  48  2.3   0.06  31.33  20.3  147
 13866     0  49  2.2  0.004   30.3  17.1  147
 13867     0  50  2.1      0  29.85  19.8  143
 13868     0  52    2      0  29.29  21.4  129
 13869     0  60    2      0  27.94  20.9  108

 [13870 rows x 16 columns],
 'NORESTE':                       date    CO    NO   NO2    NOX  O3 PM10  PM2.5    PRS  \
 0      2023-01-01 00:00:00   3.4  30.4    43   73.4   7  222    NaN  718.4
 1      2023-01-01 01:00:00   4.3  67.2  44.4  111.6   8  311    NaN  718.1
 2      2023-01-01 02:00:00  4.28  63.9  41.5  105.5   7  723    400  717.8
 3      2023-01-01 03:00:00  3.77  57.2  42.3   99.5   6  473    349  717.6
 4      2023-01-01 04:00:00  2.98  41.9  39.9   81.8   5  372    260  717.6
 ...                    ...   ...   ...   ...    ...  ..  ...    ...    ...
 13865  2024-07-31 19:00:00  0.65   7.9     6   13.9  24   83  29.67    718
 13866  2024-07-31 20:00:00  0.67   6.7   7.5   14.3  22  NaN  29.87  718.2
 13867  2024-07-31 21:00:00  0.68   7.1     9   16.1  20   76  27.98  718.6
 13868  2024-07-31 22:00:00  0.75   6.5   9.7   16.2  18   84  30.83  719.3
 13869  2024-07-31 23:00:00  0.68     7     9   16.2  22   93   34.8    720

       RAINF  RH  SO2     SR   TOUT   WSR  WDV
 0         0  61  3.8      0  19.01   4.1  190
 1         0  61   24      0  17.32   1.4  222
 2         0  69  9.8      0  16.22   2.5    4
 3         0  72  7.8      0  15.57   1.6  330
 4         0  72  7.3      0  15.53   4.1  343
 ...     ...  ..  ...    ...    ...   ...  ...
 13865     0  48  2.6  0.085  29.68  18.1  172
 13866     0  50  2.6      0  28.24  16.5  163
 13867     0  52  2.6      0  27.02  15.2  173
 13868     0  58  2.6      0  26.02  12.8  162
 13869     0  73  2.5      0  24.35  14.4  135

 [13870 rows x 16 columns],
 'CENTRO':                       date    CO   NO   NO2   NOX  O3 PM10  PM2.5    PRS  \
 0      2023-01-01 00:00:00  1.67  4.1  30.3  34.5   9  118  94.12  718.4
 1      2023-01-01 01:00:00   1.7    5  28.9  34.1   9   97  96.79  710.7
 2      2023-01-01 02:00:00  1.51  4.3  23.2  27.7  11  103  81.23  710.4
 3      2023-01-01 03:00:00   1.3  3.8  20.9  24.9  11   83  49.83  710.1
 4      2023-01-01 04:00:00  1.28  4.6  20.7  25.5   9   65  40.19  710.2
 ...                    ...   ...  ...   ...   ...  ..  ...    ...    ...
 13865  2024-07-31 19:00:00   0.6  2.5   6.4   9.2  28   77  32.42  710.7
 13866  2024-07-31 20:00:00  0.57  2.3   6.7   9.2  23   89  31.45  710.8
 13867  2024-07-31 21:00:00  0.59  1.9     6   8.2  23   90  31.75  711.2
 13868  2024-07-31 22:00:00  0.57  1.9   5.9     8  22   85  33.73  711.7
 13869  2024-07-31 23:00:00  0.55  NaN   4.8   6.9  22   85  34.73  712.3

       RAINF  RH  SO2     SR   TOUT   WSR  WDV
 0         0  45  3.3      0  17.65   4.9  236
 1         0  47  3.4  0.001  17.12   3.4  336
 2         0  46  3.4  0.001  16.69   3.4    3
 3         0  48  3.2  0.001  15.99   2.6  315
 4         0  55    3  0.001  14.74   3.9  270
 ...     ...  ..  ...    ...    ...   ...  ...
 13865     0  47  2.7  0.075  30.87    16  111
 13866     0  49  2.7   0.01  29.39  16.3  131
 13867     0  50  2.7  0.001  28.62  15.9  127
 13868     0  50  2.7  0.001     28  11.5  118
 13869     0  54  2.7  0.001  27.15  10.5  128

 [13870 rows x 16 columns],
 'NOROESTE':                       date    CO    NO   NO2    NOX  O3 PM10 PM2.5    PRS  \
 0      2023-01-01 00:00:00  4.37  60.5  46.8  107.3   5  426   421  711.8
 1      2023-01-01 01:00:00  2.88  30.1  42.1   72.2   4  393   362  711.5
 2      2023-01-01 02:00:00  2.97  33.5  40.8   74.3   4  372   312  711.1
 3      2023-01-01 03:00:00  3.15  47.6  38.5   86.1   4  260   222  710.9
 4      2023-01-01 04:00:00  2.24  24.5  34.1   58.6   3  189   143  710.9
 ...                    ...   ...   ...   ...    ...  ..  ...   ...    ...
 13865  2024-07-31 19:00:00   NaN   NaN   NaN    NaN  27   70   NaN  711.4
 13866  2024-07-31 20:00:00   NaN   NaN   NaN    NaN  23   65   NaN  711.7
 13867  2024-07-31 21:00:00   NaN   NaN   NaN    NaN  20   61   NaN  712.1
 13868  2024-07-31 22:00:00   NaN   NaN   NaN    NaN  22   65   NaN  712.7
 13869  2024-07-31 23:00:00   NaN   NaN   NaN    NaN  18   71   NaN  713.3

       RAINF   RH   SO2     SR   TOUT   WSR  WDV
 0         0   58   5.6      0  18.37   5.5  327
 1         0   59  12.8      0  17.93   7.2  322
 2         0   60   9.4      0  17.08   6.4  316
 3         0   63   6.1      0  16.24   6.1  327
 4         0   62   5.6      0  16.03   6.9  326
 ...     ...  ...   ...    ...    ...   ...  ...
 13865     0  NaN   3.4   0.08    NaN  19.8  159
 13866     0  NaN   3.3  0.004    NaN  15.8  153
 13867     0  NaN   3.3      0    NaN  11.9  142
 13868     0  NaN   3.2      0    NaN  16.9  158
 13869     0  NaN   4.3      0    NaN  12.4  130

 [13870 rows x 16 columns],
 'SUROESTE':                       date    CO    NO   NO2    NOX  O3 PM10  PM2.5    PRS  \
 0      2023-01-01 00:00:00  3.67  53.1  40.6   93.6   8  221    NaN  701.2
 1      2023-01-01 01:00:00   3.9  64.7    38  102.7   8  267    NaN  700.9
 2      2023-01-01 02:00:00  4.28  77.7  35.7  113.4   8  320    NaN  700.6
 3      2023-01-01 03:00:00  3.15    57  34.6   91.6   6  361    129  700.1
 4      2023-01-01 04:00:00  2.32  26.9  31.8   58.7   6  166     74  700.1
 ...                    ...   ...   ...   ...    ...  ..  ...    ...    ...
 13865  2024-07-31 19:00:00  0.32   3.5   8.1   11.4  28   80  32.21  700.5
 13866  2024-07-31 20:00:00  0.31   3.6   9.2   12.6  21   94  31.25  700.8
 13867  2024-07-31 21:00:00   0.3   3.3   8.8   11.8  20   85   31.1  701.2
 13868  2024-07-31 22:00:00  0.27     3   6.8    9.7  21   83  32.72  701.7
 13869  2024-07-31 23:00:00   0.3   3.1   7.2     10  20   79  33.08  702.3

       RAINF  RH  SO2     SR   TOUT   WSR  WDV
 0         0  55  4.4      0  15.66   2.9  307
 1         0  58  4.9      0  15.04   2.2  310
 2         0  58  5.5      0  15.13   2.7  270
 3         0  55  5.2      0  15.33   3.2  271
 4         0  52  5.1      0  15.53   2.5  260
 ...     ...  ..  ...    ...    ...   ...  ...
 13865     0  53  3.1  0.094  30.15  18.3   91
 13866     0  53    3  0.094   28.8    16   91
 13867     0  55  2.9  0.094  27.95  13.3   96
 13868     0  53    3    NaN   27.5  12.8   99
 13869     0  55  2.8    NaN  26.94  13.3  102

 [13870 rows x 16 columns],
 'NOROESTE2':                       date    CO    NO   NO2   NOX   O3 PM10   PM2.5    PRS  \
 0      2023-01-01 00:00:00  2.07  31.6  40.6    72    7  398   221.6  700.3
 1      2023-01-01 01:00:00  2.09  11.3  30.1  41.3    5  265  114.16  699.9
 2      2023-01-01 02:00:00  2.17  39.4  31.7  70.9    5  167   84.92  699.4
 3      2023-01-01 03:00:00  2.21  13.6    27  40.5    6  133   63.62  699.2
 4      2023-01-01 04:00:00  2.15   6.1  16.4  22.5   10   86   29.06  699.2
 ...                    ...   ...   ...   ...   ...  ...  ...     ...    ...
 13865  2024-07-31 19:00:00  0.92   3.2   8.1  11.2   21  103    15.6  700.1
 13866  2024-07-31 20:00:00     1   3.2   8.1  11.2   20  104   16.35  700.6
 13867  2024-07-31 21:00:00  0.91   3.8   8.2  11.9   19   85   14.71  701.2
 13868  2024-07-31 22:00:00  0.84   2.3   5.3   7.5   22   94   15.58  701.8
 13869  2024-07-31 23:00:00   NaN   NaN   NaN   NaN  NaN  NaN     NaN    NaN

       RAINF   RH  SO2   SR   TOUT   WSR  WDV
 0         0   53  2.1  NaN  15.93   4.6  306
 1         0   53    2  NaN  14.96   6.2  298
 2         0   54  2.1  NaN  14.51   3.4  295
 3         0   55  2.1  NaN  14.23   7.1  305
 4         0   52  2.2  NaN  14.23  12.3  303
 ...     ...  ...  ...  ...    ...   ...  ...
 13865     0   52  2.8    0  29.06  16.2   87
 13866     0   55  2.8    0  28.03    14   88
 13867     0   56  2.8    0  27.37  14.7   83
 13868     0   59  2.7    0  26.86  15.3   83
 13869   NaN  NaN  NaN  NaN    NaN   NaN  NaN

 [13870 rows x 16 columns],
 'NORTE':                       date    CO     NO   NO2    NOX   O3 PM10   PM2.5    PRS  \
 0      2023-01-01 00:00:00  7.46  130.4  43.2  173.5   12  522  369.16  715.7
 1      2023-01-01 01:00:00  4.16   56.2  41.1   97.2    9  712  299.29  715.5
 2      2023-01-01 02:00:00  3.19   42.4  37.9   80.2    7  586  201.58  715.1
 3      2023-01-01 03:00:00   3.1   46.1  34.9   80.9    7  406  186.32  714.9
 4      2023-01-01 04:00:00   3.2   59.2  33.5   92.7    7  340   168.5  714.9
 ...                    ...   ...    ...   ...    ...  ...  ...     ...    ...
 13865  2024-07-31 19:00:00  0.77      2   4.9    6.9   20   87      21  715.9
 13866  2024-07-31 20:00:00  0.79      2   5.7    7.8   18   82      23  716.5
 13867  2024-07-31 21:00:00  0.78    2.2     7    9.2   12   96      24  717.3
 13868  2024-07-31 22:00:00   NaN    NaN   NaN    NaN  NaN  NaN     NaN    NaN
 13869  2024-07-31 23:00:00   NaN    NaN   NaN    NaN  NaN  NaN     NaN    NaN

       RAINF   RH  SO2   SR   TOUT   WSR  WDV
 0         0  NaN  4.2    0  17.05   3.8   18
 1         0  NaN    4    0  15.87   4.5   15
 2         0  NaN  3.8    0  15.41   4.8   28
 3         0  NaN  3.7    0  14.58   2.8   26
 4         0  NaN  3.8    0  13.84   4.1   28
 ...     ...  ...  ...  ...    ...   ...  ...
 13865     0  NaN  2.8    0  29.77  16.1  141
 13866     0  NaN  2.8    0  28.95  13.9  149
 13867     0  NaN  2.6    0  27.59  12.2  130
 13868   NaN  NaN  NaN  NaN    NaN   NaN  NaN
 13869   NaN  NaN  NaN  NaN    NaN   NaN  NaN

 [13870 rows x 16 columns],
 'NORESTE2':                       date    CO    NO   NO2   NOX   O3 PM10 PM2.5    PRS  \
 0      2023-01-01 00:00:00  2.12  10.2  34.1  44.3   12   93    67  714.1
 1      2023-01-01 01:00:00  1.97   6.7  34.3  40.9   10  162   101  713.8
 2      2023-01-01 02:00:00  2.21  17.6  34.1  51.7    8  209   143  713.4
 3      2023-01-01 03:00:00  2.41  34.9  32.3  67.3    8  220   154    713
 4      2023-01-01 04:00:00  2.57  47.9    34  81.9    8  219   166    713
 ...                    ...   ...   ...   ...   ...  ...  ...   ...    ...
 13865  2024-07-31 19:00:00   NaN  11.3  13.7  24.9   16  173    10  713.9
 13866  2024-07-31 20:00:00   NaN  12.8  13.9  26.8   13  154    30  714.8
 13867  2024-07-31 21:00:00   NaN  12.1  11.4  23.5   10  NaN    29  715.6
 13868  2024-07-31 22:00:00   NaN   NaN   NaN   NaN  NaN  NaN   NaN    NaN
 13869  2024-07-31 23:00:00   NaN   NaN   NaN   NaN  NaN  NaN   NaN    NaN

       RAINF   RH  SO2     SR   TOUT   WSR  WDV
 0         0   57  3.1      0  20.21    14  316
 1         0   62  3.8      0  18.19   7.3  259
 2         0   68  3.7      0  16.41    10  126
 3         0   73  3.6  0.019  16.42  13.1   90
 4         0   73  3.5      0  15.03  14.6  139
 ...     ...  ...  ...    ...    ...   ...  ...
 13865     0   45    3      0  30.32  20.1  309
 13866     0   53  4.1      0  29.02  15.8  296
 13867     0   69  5.1      0  27.25  12.9  289
 13868   NaN  NaN  NaN    NaN    NaN   NaN  NaN
 13869   NaN  NaN  NaN    NaN    NaN   NaN  NaN

 [13870 rows x 16 columns],
 'SURESTE2':                       date    CO     NO   NO2    NOX   O3 PM10 PM2.5    PRS  \
 0      2023-01-01 00:00:00  2.91   36.6  33.6   70.2   10  100   NaN  714.1
 1      2023-01-01 01:00:00   4.8   94.3  32.7    127   13  198   NaN    722
 2      2023-01-01 02:00:00  6.58    144  29.6  173.6   13  436   NaN  721.9
 3      2023-01-01 03:00:00  6.95  173.2  27.4  200.6   11  558   NaN  721.7
 4      2023-01-01 04:00:00  6.77  151.7  23.6  175.3   12  551   NaN  721.7
 ...                    ...   ...    ...   ...    ...  ...  ...   ...    ...
 13865  2024-07-31 19:00:00  0.65    5.6   3.9    9.5   22  106    38  722.2
 13866  2024-07-31 20:00:00  0.61    3.5   3.4    6.8   22  107    42  722.4
 13867  2024-07-31 21:00:00  0.53    2.1   1.4    3.5   24  122    41  722.7
 13868  2024-07-31 22:00:00   NaN    NaN   NaN    NaN  NaN  NaN   NaN    NaN
 13869  2024-07-31 23:00:00   NaN    NaN   NaN    NaN  NaN  NaN   NaN    NaN

       RAINF   RH  SO2   SR   TOUT   WSR  WDR
 0         0   57    3    0  18.64   1.4   55
 1         0   68  3.9    0  17.34   0.5   14
 2         0   70    5    0   16.6   1.3  227
 3         0   73  5.1    0  15.81   1.4  237
 4         0   75  4.7    0     15   1.4  234
 ...     ...  ...  ...  ...    ...   ...  ...
 13865     0   52  1.8    0  29.97  10.9  152
 13866     0   60  2.2    0  28.85   9.1  132
 13867     0   74  6.8    0  27.31  10.8  114
 13868   NaN  NaN  NaN  NaN    NaN   NaN  NaN
 13869   NaN  NaN  NaN  NaN    NaN   NaN  NaN

 [13870 rows x 16 columns],
 'SUROESTE2':                       date    CO   NO   NO2   NOX   O3 PM10 PM2.5    PRS  \
 0      2023-01-01 00:00:00  1.14  3.9  15.8  19.6   17   64    34  713.5
 1      2023-01-01 01:00:00  1.04  3.8    13  16.8   19   71    30  713.5
 2      2023-01-01 02:00:00  1.03  5.2  15.5  20.6   16   85    32  713.3
 3      2023-01-01 03:00:00  1.03  3.9  15.9  19.8   16   57    30  713.1
 4      2023-01-01 04:00:00  0.85  3.8  11.3  15.1   19   59    20  713.1
 ...                    ...   ...  ...   ...   ...  ...  ...   ...    ...
 13865  2024-07-31 19:00:00   0.5  3.7   5.9   9.6   22   85    16  713.8
 13866  2024-07-31 20:00:00  0.48  5.1   7.4  12.5   20   82    19    714
 13867  2024-07-31 21:00:00  0.46  3.3   6.4   9.8   21   74    24  714.2
 13868  2024-07-31 22:00:00   NaN  NaN   NaN   NaN  NaN  NaN   NaN    NaN
 13869  2024-07-31 23:00:00   NaN  NaN   NaN   NaN  NaN  NaN   NaN    NaN

       RAINF   RH  SO2   SR   TOUT   WSR  WDR
 0         0   45  3.9    0  16.96   5.5  250
 1         0   46  3.8    0  16.78   4.9  248
 2         0   47  3.8    0  16.22   4.6  236
 3         0   44  3.8    0  16.99     5  229
 4         0   44  3.7    0  16.74   5.5  203
 ...     ...  ...  ...  ...    ...   ...  ...
 13865     0   53  2.4    0  28.34  12.8  194
 13866     0   52  2.3    0  27.95  14.5  180
 13867     0   53  2.3    0  27.38  14.1  188
 13868   NaN  NaN  NaN  NaN    NaN   NaN  NaN
 13869   NaN  NaN  NaN  NaN    NaN   NaN  NaN

 [13870 rows x 16 columns],
 'SURESTE 3':                       date    CO    NO   NO2   NOX   O3 PM10 PM2.5    PRS  \
 0      2023-01-01 00:00:00  3.08  13.8  30.9  44.7    5  206   144  731.1
 1      2023-01-01 01:00:00  2.34    16  23.3  39.1    7  293   190  730.7
 2      2023-01-01 02:00:00  1.82   6.1  17.5  23.3    8  257    93  730.6
 3      2023-01-01 03:00:00  2.52  23.6  24.2  47.6    4   89    85  730.3
 4      2023-01-01 04:00:00  3.25  35.7  23.1  58.7    4  204   145  730.2
 ...                    ...   ...   ...   ...   ...  ...  ...   ...    ...
 13865  2024-07-31 19:00:00   NaN   3.8   5.1   8.7   24  114    11  731.2
 13866  2024-07-31 20:00:00   NaN     3   4.4   7.2   41  118    20  731.8
 13867  2024-07-31 21:00:00   NaN   2.8   3.3     6   17  116    33  732.6
 13868  2024-07-31 22:00:00   NaN   NaN   NaN   NaN  NaN  NaN   NaN    NaN
 13869  2024-07-31 23:00:00   NaN   NaN   NaN   NaN  NaN  NaN   NaN    NaN

       RAINF   RH   SO2     SR   TOUT   WSR  WDR
 0         0   64   5.8      0  18.22   3.2  354
 1         0   67   6.9  0.001  17.13   4.7  359
 2         0   72   5.2  0.001  15.68   4.3  313
 3         0   77   4.5  0.001  14.23     4  303
 4         0   80   4.2  0.001  13.36   5.2  291
 ...     ...  ...   ...    ...    ...   ...  ...
 13865     0   53   3.6  0.001   29.7  12.4  124
 13866     0   67  10.6  0.001  28.29  13.2  101
 13867     0   74  10.6  0.001  27.15  12.9   98
 13868   NaN  NaN   NaN    NaN    NaN   NaN  NaN
 13869   NaN  NaN   NaN    NaN    NaN   NaN  NaN

 [13870 rows x 16 columns],
 'SUR':                       date    CO   NO    NO2    NOX   O3 PM10 PM2.5    PRS  \
 0      2023-01-01 00:00:00  2.04  7.2  136.1  143.3    6   56    36  712.1
 1      2023-01-01 01:00:00  2.01  8.3  107.9    116    6   82    51  711.9
 2      2023-01-01 02:00:00  1.89  9.2    136  144.9    6   90    57  711.5
 3      2023-01-01 03:00:00   1.7  7.3   96.5  103.5    7   76    39  711.2
 4      2023-01-01 04:00:00  1.66    6  122.2    128    6   45    20  711.1
 ...                    ...   ...  ...    ...    ...  ...  ...   ...    ...
 13865  2024-07-31 19:00:00  0.58  4.5      9   13.5   18  111   NaN  712.5
 13866  2024-07-31 20:00:00  0.57  4.2   10.5   14.6   14   97   NaN  713.1
 13867  2024-07-31 21:00:00   NaN  NaN    NaN    NaN  NaN  NaN   NaN    NaN
 13868  2024-07-31 22:00:00   NaN  NaN    NaN    NaN  NaN  NaN   NaN    NaN
 13869  2024-07-31 23:00:00   NaN  NaN    NaN    NaN  NaN  NaN   NaN    NaN

       RAINF   RH  SO2     SR   TOUT   WSR  WDR
 0         0   64  2.4      0  15.05   1.2  251
 1         0   69  2.5  0.001  14.23   2.2  275
 2         0   73  2.5  0.001   13.5   2.1  235
 3         0   70  2.5  0.001  13.23   3.2  181
 4         0   71  2.5  0.001  12.38   2.6  257
 ...     ...  ...  ...    ...    ...   ...  ...
 13865     0   52  3.6  0.002   28.5  12.8  155
 13866     0   57  3.7  0.002  27.28  10.1  172
 13867   NaN  NaN  NaN    NaN    NaN   NaN  NaN
 13868   NaN  NaN  NaN    NaN    NaN   NaN  NaN
 13869   NaN  NaN  NaN    NaN    NaN   NaN  NaN

 [13870 rows x 16 columns],
 'NORTE2':                       date    CO    NO   NO2    NOX   O3 PM10 PM2.5    PRS  \
 0      2023-01-01 00:00:00  4.48    73  49.8  122.9   14  228   188  712.1
 1      2023-01-01 01:00:00  4.86  64.7  47.3    112   13  478   341  711.8
 2      2023-01-01 02:00:00  3.77  44.9  43.1     88   11  566   352  711.5
 3      2023-01-01 03:00:00  3.71  63.7  42.1  105.9   11  498   290  711.2
 4      2023-01-01 04:00:00  4.36  91.7  40.4  132.3   11  483   308  711.2
 ...                    ...   ...   ...   ...    ...  ...  ...   ...    ...
 13865  2024-07-31 19:00:00  0.98   3.7  17.2   20.9   17   99    24  712.4
 13866  2024-07-31 20:00:00  1.08   3.7  15.8   19.5   19   98    24    713
 13867  2024-07-31 21:00:00   1.2   5.5    19   24.5   20  101    54  713.6
 13868  2024-07-31 22:00:00   NaN   NaN   NaN    NaN  NaN  NaN   NaN    NaN
 13869  2024-07-31 23:00:00   NaN   NaN   NaN    NaN  NaN  NaN   NaN    NaN

       RAINF   RH  SO2   SR   TOUT   WSR  WDR
 0         0   54  4.5    0  18.16   5.5  221
 1         0   58  5.8    0  17.84   2.2  272
 2         0   62    6    0  16.87   3.7  221
 3         0   60  6.1    0  16.61   2.5  290
 4         0   67    5    0  15.24   1.9  280
 ...     ...  ...  ...  ...    ...   ...  ...
 13865     0   49  3.1    0  29.35  10.3  122
 13866     0   51  3.1    0  28.82  12.5  107
 13867     0   61  3.8    0  27.67  10.4   85
 13868   NaN  NaN  NaN  NaN    NaN   NaN  NaN
 13869   NaN  NaN  NaN  NaN    NaN   NaN  NaN

 [13870 rows x 16 columns],
 'NORESTE3':                       date     CO    NO   NO2   NOX    O3 PM10 PM2.5  PRS  \
 0      2023-01-01 00:00:00  0.832  12.7  14.9  26.4   5.9   73   NaN  729
 1      2023-01-01 01:00:00  1.319  19.1  18.1  36.4   4.9   92   NaN  729

Finally, we will turn the data type of the data into datatime, and remove "CATALOGO" because it's not relevant for the computational analysis. Regarding the information of the other data I can't check the information of the other variables, since they are numeric but habe labels according to specific situations.

In [11]:
import pandas as pd

db_2023_2024.pop("CATÁLOGO", None)
db_2020_2022.pop("CATÁLOGO", None)


# Convertir 'date' a datetime en db_2023_2024
for station in db_2023_2024:
    try:
        db_2023_2024[station]['date'] = pd.to_datetime(
            db_2023_2024[station]['date'], 
            format='%d/%m/%y %H:%M', 
            errors='coerce'
        )
        print(f"Conversión exitosa para {station} en db_2023_2024")
    except Exception as e:
        print(f"Error en {station} (db_2023_2024): {e}")

# Convertir 'date' a datetime en db_2020_2022
for station in db_2020_2022:
    try:
        db_2020_2022[station]['date'] = pd.to_datetime(
            db_2020_2022[station]['date'], 
            format='%d/%m/%y %H:%M', 
            errors='coerce'
        )
        print(f"Conversión exitosa para {station} en db_2020_2022")
    except Exception as e:
        print(f"Error en {station} (db_2020_2022): {e}")

Conversión exitosa para SURESTE en db_2023_2024
Conversión exitosa para NORESTE en db_2023_2024
Conversión exitosa para CENTRO en db_2023_2024
Conversión exitosa para NOROESTE en db_2023_2024
Conversión exitosa para SUROESTE en db_2023_2024
Conversión exitosa para NOROESTE2 en db_2023_2024
Conversión exitosa para NORTE en db_2023_2024
Conversión exitosa para NORESTE2 en db_2023_2024
Conversión exitosa para SURESTE2 en db_2023_2024
Conversión exitosa para SUROESTE2 en db_2023_2024
Conversión exitosa para SURESTE 3 en db_2023_2024
Conversión exitosa para SUR en db_2023_2024
Conversión exitosa para NORTE2 en db_2023_2024
Conversión exitosa para NORESTE3 en db_2023_2024
Conversión exitosa para NOROESTE3 en db_2023_2024
Conversión exitosa para SURESTE en db_2020_2022
Conversión exitosa para NORESTE en db_2020_2022
Conversión exitosa para CENTRO en db_2020_2022
Conversión exitosa para NOROESTE en db_2020_2022
Conversión exitosa para SUROESTE en db_2020_2022
Conversión exitosa para NOROESTE2 en db_2020_2022
Conversión exitosa para NORTE en db_2020_2022
Conversión exitosa para SUROESTE2 en db_2020_2022
Conversión exitosa para SURESTE2 en db_2020_2022
Conversión exitosa para SURESTE3 en db_2020_2022
Conversión exitosa para SUR en db_2020_2022
Conversión exitosa para NORTE2 en db_2020_2022
Conversión exitosa para NORESTE2 en db_2020_2022
Conversión exitosa para NORESTE3 en db_2020_2022
Conversión exitosa para NOROESTE3 en db_2020_2022

/var/folders/n0/06qt81n12nb7sf11vf0gz8240000gn/T/ipykernel_83542/3972273864.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  db_2020_2022[station]['date'] = pd.to_datetime(

## Exploratory Analysis of Data

For this part of the analysis, we are going to explore the data, with the aim of finding patterns and see which database and station is the most complete. Also, we will check tha mean concentration of gases in days after new politics or problems were imposed.

In [12]:
#Final DataBases (db_2023_2024, db_2020_2022)

# SIMA gave us a chart with multiple meanings of the non-numeric data in the DB, we will write down the meanings for further exploration.

import pandas as pd

# ------------------Chart 1 (Stations)
df_estaciones = pd.DataFrame({
    "Abreviatura": ["SE", "NE", "CE", "NO", "SO", "NO2", "NTE", "NE2", "SE2", "SO2", "SE", "NTE2", "SE3"],
    "Descripción": ["Sureste", "Noreste", "Centro", "Noroeste", "Suroeste", "Noroeste 2", "Norte", "Noreste 2", 
                    "Sureste 2", "Suroeste 2", "Sur", "Norte 2", "Sureste 3"],
    "Estación": ["La Pastora", "San Nicolás", "Obispado", "San Bernabé", "Santa Catarina", "García", "Escobedo", 
                 "Apodaca", "Juárez", "San Pedro", "Pueblo Serena", "Universidad", "Cadereyta"],
    "Municipio": ["Guadalupe", "San Nicolás de los Garzas", "Monterrey", "Monterrey", "Santa Catarina", "García", 
                  "Escobedo", "Apodaca", "Juárez", "San Pedro Garza García", None, None, None]
})

# ------------------Chart 2 (Pollutants)
df_contaminantes = pd.DataFrame({
    "Abreviatura": ["PM10", "PM2.5", "O3*", "SO2*", "NO2*", "CO", "NO", "NOx"],
    "Contaminante": ["Material Particulado menor a 10 micrométros", 
                     "Material Particulado menor a 2.5 micrométros", 
                     "Ozono", 
                     "Dióxido de Azufre", 
                     "Dióxido de Nitrógeno", 
                     "Monóxido de Carbono", 
                     "Monóxido de Nitrógeno", 
                     "Es la suma de NO + NO2"],
    "Unidad": ["µg/m3", "µg/m3", "ppb", "ppb", "ppb", "ppm", "ppb", "ppb"]
})

# ------------------Chart 3 (Meteorological Parameters)
df_meteo = pd.DataFrame({
    "Abreviatura": ["TOUT", "RH", "SR", "RAINF**", "PRS", "WSR", "WDR"],
    "Contaminante": ["Temperatura", "Humedad Relativa", "Radiación Solar", "Precipitación", 
                     "Presión Atmosférica", "Velocidad del Viento", "Dirección del Viento"],
    "Unidad": ["ºC", "%", "kW/m2", "mm/Hr", "mm Hg", "Km/hr", "º"]
})

# ------------------Chart 4 (Flags)
df_flags = pd.DataFrame({
    "Flag": ["P", "p", "C", "c", "D", "d", "B", "b", "m", "l", "z", "o", "s", "r", "e", "a", "s", "f", "h", "n", "x"],
    "Description": ["Falla eléctrica", "Falla eléctrica", "Calibración", "Calibración", "Apagado", "Apagado", 
                    "Malas condiciones", "Malas condiciones", "Positivo sobre el rango", "Negativo sobre el rango", 
                    "Ceros y negativos", "PM10 mayor a 900 ug/m3", "Valores repetidos", 
                    "comparativo PM10 vs PM2.5", "Eliminar datos NO y Nox", 
                    "Eliminar PM menor a 5 ug/m3 y 0.05 ppm en CO", 
                    "Valores iguales consecutivos", 
                    "Valores 3 veces mayor que el valor anterior para PM10", 
                    "Valores de temperatura con más de 10 grados o 10 mmHg de diferencia de una hora", 
                    "falla de comunicación", 
                    "Valor que ya no esta manualmente, sí paso los protocolos, pero no debe estar ahí"],
    "Hora": ["Valida", "Invalida", "Valida", "Invalida", "Valida", "Invalida", "Valida", "Invalida", "Invalida", 
             "Invalida", "Invalida", "Invalida", "Invalida", "Invalida", "Invalida", "Invalida", "Invalida", 
             "Invalida", "Invalida", "Invalida", "Invalida"]
})

# Lista de banderas inválidas (Tabla 3)
invalid_flags = ['p', 'c', 'd', 'b', 'm', 'l', 'z', 'o', 's', 'r', 'e', 'a', 'f', 'h', 'n', 'x']
quant_vars = ['CO', 'NO', 'NO2', 'NOX', 'O3', 'PM10', 'PM2.5', 'SO2', 'PRS', 'RAINF', 'RH', 'SR', 'TOUT', 'WSR', 'WDR']
key_vars = ['NO2', 'PM2.5', 'SO2']  # Enfocadas en tráfico y refinería
# Mostrar un preview
print(df_estaciones.head())
print(df_contaminantes.head())
print(df_meteo.head())
print(df_flags.head())

  Abreviatura Descripción        Estación                  Municipio
0          SE     Sureste      La Pastora                  Guadalupe
1          NE     Noreste     San Nicolás  San Nicolás de los Garzas
2          CE      Centro        Obispado                  Monterrey
3          NO    Noroeste     San Bernabé                  Monterrey
4          SO    Suroeste  Santa Catarina             Santa Catarina
  Abreviatura                                  Contaminante Unidad
0        PM10   Material Particulado menor a 10 micrométros  µg/m3
1       PM2.5  Material Particulado menor a 2.5 micrométros  µg/m3
2         O3*                                         Ozono    ppb
3        SO2*                             Dióxido de Azufre    ppb
4        NO2*                          Dióxido de Nitrógeno    ppb
  Abreviatura         Contaminante Unidad
0        TOUT          Temperatura     ºC
1          RH     Humedad Relativa      %
2          SR      Radiación Solar  kW/m2
3     RAINF**        Precipitación  mm/Hr
4         PRS  Presión Atmosférica  mm Hg
  Flag      Description      Hora
0    P  Falla eléctrica    Valida
1    p  Falla eléctrica  Invalida
2    C      Calibración    Valida
3    c      Calibración  Invalida
4    D          Apagado    Valida

In [13]:

#This definition receives a dictionary with dataframes of each stations and a vector of the years corresponding to that dataset.
def dataExploration(diccionarioEstaciones, years):
    h=1
    #1. Dimension of dataset
    
    #2. Description of DB
    #3. Quality of Dataset (Missing values)

Para este análisis, como es para industrias nos enfocaremos en: CO, NO, NO2, NOX, O3,SO2,PM10,PM2.5 que son las que mayor impacto generan a nivel de contaminación y que son  mayormente producidos por las industrias.

In [16]:
variables_importantes = ['CO', 'NO', 'NO2', 'NOX', 'O3', 'SO2', 'PM10', 'PM2.5']

# Crear copias de los diccionarios con solo las variables de interés
db_2023_2024_variablesImportantes = {}
db_2020_2022_variablesImportantes = {}

# Copiar y filtrar para 2023-2024
for station in db_2023_2024:
    # Crear una copia del dataframe con solo las columnas especificadas
    db_2023_2024_variablesImportantes[station] = db_2023_2024[station][variables_importantes].copy()

# Copiar y filtrar para 2020-2022
for station in db_2020_2022:
    # Crear una copia del dataframe con solo las columnas especificadas
    db_2020_2022_variablesImportantes[station] = db_2020_2022[station][variables_importantes].copy()

# Imprimir información para verificar
print("="*80, "Dataset 2023-2024 después de conversión")
for station in db_2023_2024_variablesImportantes:
    print("-"*50, station)
    print("-"*25, "Tipos de Datos")
    print(db_2023_2024_variablesImportantes[station].info())

print("="*80, "Dataset 2020-2022 después de conversión")
for station in db_2020_2022_variablesImportantes:
    print("-"*50, station)
    print("-"*25, "Tipos de Datos")
    print(db_2020_2022_variablesImportantes[station].info())

================================================================================ Dataset 2023-2024 después de conversión
-------------------------------------------------- SURESTE
------------------------- Tipos de Datos
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13870 entries, 0 to 13869
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   CO      13685 non-null  object
 1   NO      13504 non-null  object
 2   NO2     13717 non-null  object
 3   NOX     13716 non-null  object
 4   O3      13464 non-null  object
 5   SO2     13648 non-null  object
 6   PM10    13488 non-null  object
 7   PM2.5   10188 non-null  object
dtypes: object(8)
memory usage: 867.0+ KB
None
-------------------------------------------------- NORESTE
------------------------- Tipos de Datos
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13870 entries, 0 to 13869
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   CO      13282 non-null  object
 1   NO      13582 non-null  object
 2   NO2     13654 non-null  object
 3   NOX     13652 non-null  object
 4   O3      13198 non-null  object
 5   SO2     13474 non-null  object
 6   PM10    13434 non-null  object
 7   PM2.5   12314 non-null  object
dtypes: object(8)
memory usage: 867.0+ KB
None
-------------------------------------------------- CENTRO
------------------------- Tipos de Datos
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13870 entries, 0 to 13869
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   CO      13542 non-null  object
 1   NO      13100 non-null  object
 2   NO2     13537 non-null  object
 3   NOX     13535 non-null  object
 4   O3      13314 non-null  object
 5   SO2     13363 non-null  object
 6   PM10    13514 non-null  object
 7   PM2.5   11284 non-null  object
dtypes: object(8)
memory usage: 867.0+ KB
None
-------------------------------------------------- NOROESTE
------------------------- Tipos de Datos
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13870 entries, 0 to 13869
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   CO      12270 non-null  object
 1   NO      11971 non-null  object
 2   NO2     12238 non-null  object
 3   NOX     12235 non-null  object
 4   O3      12614 non-null  object
 5   SO2     13042 non-null  object
 6   PM10    13128 non-null  object
 7   PM2.5   5407 non-null   object
dtypes: object(8)
memory usage: 867.0+ KB
None
-------------------------------------------------- SUROESTE
------------------------- Tipos de Datos
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13870 entries, 0 to 13869
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   CO      13577 non-null  object
 1   NO      13369 non-null  object
 2   NO2     13354 non-null  object
 3   NOX     13354 non-null  object
 4   O3      13089 non-null  object
 5   SO2     13466 non-null  object
 6   PM10    13488 non-null  object
 7   PM2.5   11739 non-null  object
dtypes: object(8)
memory usage: 867.0+ KB
None
-------------------------------------------------- NOROESTE2
------------------------- Tipos de Datos
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13870 entries, 0 to 13869
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   CO      13548 non-null  object
 1   NO      13363 non-null  object
 2   NO2     13589 non-null  object
 3   NOX     13591 non-null  object
 4   O3      13437 non-null  object
 5   SO2     13400 non-null  object
 6   PM10    13543 non-null  object
 7   PM2.5   10719 non-null  object
dtypes: object(8)
memory usage: 867.0+ KB
None
-------------------------------------------------- NORTE
------------------------- Tipos de Datos
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13870 entries, 0 to 13869
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   CO      13257 non-null  object
 1   NO      13221 non-null  object
 2   NO2     13355 non-null  object
 3   NOX     13350 non-null  object
 4   O3      13043 non-null  object
 5   SO2     12947 non-null  object
 6   PM10    13156 non-null  object
 7   PM2.5   12536 non-null  object
dtypes: object(8)
memory usage: 867.0+ KB
None
-------------------------------------------------- NORESTE2
------------------------- Tipos de Datos
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13870 entries, 0 to 13869
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   CO      11833 non-null  object
 1   NO      13452 non-null  object
 2   NO2     13471 non-null  object
 3   NOX     13473 non-null  object
 4   O3      12711 non-null  object
 5   SO2     13339 non-null  object
 6   PM10    13244 non-null  object
 7   PM2.5   12120 non-null  object
dtypes: object(8)
memory usage: 867.0+ KB
None
-------------------------------------------------- SURESTE2
------------------------- Tipos de Datos
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13870 entries, 0 to 13869
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   CO      12362 non-null  object
 1   NO      13384 non-null  object
 2   NO2     13334 non-null  object
 3   NOX     13587 non-null  object
 4   O3      13057 non-null  object
 5   SO2     13622 non-null  object
 6   PM10    13490 non-null  object
 7   PM2.5   12966 non-null  object
dtypes: object(8)
memory usage: 867.0+ KB
None
-------------------------------------------------- SUROESTE2
------------------------- Tipos de Datos
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13870 entries, 0 to 13869
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   CO      13685 non-null  object
 1   NO      13603 non-null  object
 2   NO2     13754 non-null  object
 3   NOX     13751 non-null  object
 4   O3      13627 non-null  object
 5   SO2     13745 non-null  object
 6   PM10    13228 non-null  object
 7   PM2.5   12606 non-null  object
dtypes: object(8)
memory usage: 867.0+ KB
None
-------------------------------------------------- SURESTE 3
------------------------- Tipos de Datos
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13870 entries, 0 to 13869
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   CO      12903 non-null  object
 1   NO      13412 non-null  object
 2   NO2     13549 non-null  object
 3   NOX     13552 non-null  object
 4   O3      13387 non-null  object
 5   SO2     13536 non-null  object
 6   PM10    13523 non-null  object
 7   PM2.5   12831 non-null  object
dtypes: object(8)
memory usage: 867.0+ KB
None
-------------------------------------------------- SUR
------------------------- Tipos de Datos
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13870 entries, 0 to 13869
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   CO      12523 non-null  object
 1   NO      13260 non-null  object
 2   NO2     13415 non-null  object
 3   NOX     13410 non-null  object
 4   O3      13598 non-null  object
 5   SO2     13675 non-null  object
 6   PM10    13626 non-null  object
 7   PM2.5   10560 non-null  object
dtypes: object(8)
memory usage: 867.0+ KB
None
-------------------------------------------------- NORTE2
------------------------- Tipos de Datos
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13870 entries, 0 to 13869
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   CO      13470 non-null  object
 1   NO      13718 non-null  object
 2   NO2     13730 non-null  object
 3   NOX     13730 non-null  object
 4   O3      13385 non-null  object
 5   SO2     13684 non-null  object
 6   PM10    13519 non-null  object
 7   PM2.5   12500 non-null  object
dtypes: object(8)
memory usage: 867.0+ KB
None
-------------------------------------------------- NORESTE3
------------------------- Tipos de Datos
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13870 entries, 0 to 13869
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   CO      13358 non-null  object
 1   NO      13031 non-null  object
 2   NO2     13032 non-null  object
 3   NOX     13024 non-null  object
 4   O3      13258 non-null  object
 5   SO2     8491 non-null   object
 6   PM10    13081 non-null  object
 7   PM2.5   0 non-null      object
dtypes: object(8)
memory usage: 867.0+ KB
None
-------------------------------------------------- NOROESTE3
------------------------- Tipos de Datos
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13870 entries, 0 to 13869
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   CO      12278 non-null  object
 1   NO      12351 non-null  object
 2   NO2     12376 non-null  object
 3   NOX     12372 non-null  object
 4   O3      12232 non-null  object
 5   SO2     12506 non-null  object
 6   PM10    13054 non-null  object
 7   PM2.5   668 non-null    object
dtypes: object(8)
memory usage: 867.0+ KB
None
================================================================================ Dataset 2020-2022 después de conversión
-------------------------------------------------- SURESTE
------------------------- Tipos de Datos
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26298 entries, 0 to 26297
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   CO      24734 non-null  float64
 1   NO      14369 non-null  float64
 2   NO2     15276 non-null  float64
 3   NOX     15277 non-null  float64
 4   O3      24929 non-null  float64
 5   SO2     23746 non-null  float64
 6   PM10    25142 non-null  float64
 7   PM2.5   24471 non-null  float64
dtypes: float64(8)
memory usage: 1.6 MB
None
-------------------------------------------------- NORESTE
------------------------- Tipos de Datos
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26295 entries, 0 to 26294
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   CO      21724 non-null  float64
 1   NO      19846 non-null  float64
 2   NO2     15984 non-null  float64
 3   NOX     15987 non-null  float64
 4   O3      15791 non-null  float64
 5   SO2     15924 non-null  float64
 6   PM10    25331 non-null  float64
 7   PM2.5   24809 non-null  float64
dtypes: float64(8)
memory usage: 1.6 MB
None
-------------------------------------------------- CENTRO
------------------------- Tipos de Datos
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26296 entries, 0 to 26295
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   CO      25371 non-null  float64
 1   NO      22731 non-null  float64
 2   NO2     23880 non-null  float64
 3   NOX     24085 non-null  float64
 4   O3      23470 non-null  float64
 5   SO2     23525 non-null  float64
 6   PM10    25444 non-null  float64
 7   PM2.5   22790 non-null  float64
dtypes: float64(8)
memory usage: 1.6 MB
None
-------------------------------------------------- NOROESTE
------------------------- Tipos de Datos
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26297 entries, 0 to 26296
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   CO      15858 non-null  float64
 1   NO      19323 non-null  float64
 2   NO2     16833 non-null  float64
 3   NOX     17062 non-null  float64
 4   O3      15333 non-null  float64
 5   SO2     18474 non-null  float64
 6   PM10    24429 non-null  float64
 7   PM2.5   22771 non-null  float64
dtypes: float64(8)
memory usage: 1.6 MB
None
-------------------------------------------------- SUROESTE
------------------------- Tipos de Datos
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26297 entries, 0 to 26296
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   CO      20214 non-null  float64
 1   NO      22388 non-null  float64
 2   NO2     21361 non-null  float64
 3   NOX     20852 non-null  float64
 4   O3      22496 non-null  float64
 5   SO2     23202 non-null  float64
 6   PM10    25364 non-null  float64
 7   PM2.5   24713 non-null  float64
dtypes: float64(8)
memory usage: 1.6 MB
None
-------------------------------------------------- NOROESTE2
------------------------- Tipos de Datos
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26295 entries, 0 to 26294
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   CO      25557 non-null  float64
 1   NO      24412 non-null  float64
 2   NO2     21970 non-null  float64
 3   NOX     24421 non-null  float64
 4   O3      23783 non-null  float64
 5   SO2     21489 non-null  float64
 6   PM10    25490 non-null  float64
 7   PM2.5   23670 non-null  float64
dtypes: float64(8)
memory usage: 1.6 MB
None
-------------------------------------------------- NORTE
------------------------- Tipos de Datos
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26296 entries, 0 to 26295
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   CO      15143 non-null  float64
 1   NO      14292 non-null  float64
 2   NO2     14291 non-null  float64
 3   NOX     14279 non-null  float64
 4   O3      15523 non-null  float64
 5   SO2     14341 non-null  float64
 6   PM10    22998 non-null  float64
 7   PM2.5   20715 non-null  float64
dtypes: float64(8)
memory usage: 1.6 MB
None
-------------------------------------------------- SUROESTE2
------------------------- Tipos de Datos
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26295 entries, 0 to 26294
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   CO      25031 non-null  float64
 1   NO      20870 non-null  float64
 2   NO2     21299 non-null  float64
 3   NOX     21303 non-null  float64
 4   O3      25581 non-null  float64
 5   SO2     22658 non-null  float64
 6   PM10    24707 non-null  float64
 7   PM2.5   22483 non-null  float64
dtypes: float64(8)
memory usage: 1.6 MB
None
-------------------------------------------------- SURESTE2
------------------------- Tipos de Datos
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26296 entries, 0 to 26295
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   CO      15958 non-null  float64
 1   NO      15723 non-null  float64
 2   NO2     15837 non-null  float64
 3   NOX     15843 non-null  float64
 4   O3      13589 non-null  float64
 5   SO2     23431 non-null  float64
 6   PM10    24285 non-null  float64
 7   PM2.5   20957 non-null  float64
dtypes: float64(8)
memory usage: 1.6 MB
None
-------------------------------------------------- SURESTE3
------------------------- Tipos de Datos
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26295 entries, 0 to 26294
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   CO      24611 non-null  float64
 1   NO      25062 non-null  float64
 2   NO2     25211 non-null  float64
 3   NOX     25231 non-null  float64
 4   O3      23117 non-null  float64
 5   SO2     23661 non-null  float64
 6   PM10    24926 non-null  float64
 7   PM2.5   22985 non-null  float64
dtypes: float64(8)
memory usage: 1.6 MB
None
-------------------------------------------------- SUR
------------------------- Tipos de Datos
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26294 entries, 0 to 26293
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   CO      16936 non-null  float64
 1   NO      15436 non-null  float64
 2   NO2     15450 non-null  float64
 3   NOX     16895 non-null  float64
 4   O3      15862 non-null  float64
 5   SO2     13757 non-null  float64
 6   PM10    25454 non-null  float64
 7   PM2.5   15900 non-null  float64
dtypes: float64(8)
memory usage: 1.6 MB
None
-------------------------------------------------- NORTE2
------------------------- Tipos de Datos
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26295 entries, 0 to 26294
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   CO      24012 non-null  float64
 1   NO      17718 non-null  float64
 2   NO2     17242 non-null  float64
 3   NOX     17244 non-null  float64
 4   O3      17058 non-null  float64
 5   SO2     13889 non-null  float64
 6   PM10    25067 non-null  float64
 7   PM2.5   21306 non-null  float64
dtypes: float64(8)
memory usage: 1.6 MB
None
-------------------------------------------------- NORESTE2
------------------------- Tipos de Datos
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26295 entries, 0 to 26294
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   CO      22665 non-null  float64
 1   NO      15827 non-null  float64
 2   NO2     15807 non-null  float64
 3   NOX     16230 non-null  float64
 4   O3      16554 non-null  float64
 5   SO2     21174 non-null  float64
 6   PM10    24790 non-null  float64
 7   PM2.5   22123 non-null  float64
dtypes: float64(8)
memory usage: 1.6 MB
None
-------------------------------------------------- NORESTE3
------------------------- Tipos de Datos
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26302 entries, 0 to 26301
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   CO      19293 non-null  float64
 1   NO      19367 non-null  float64
 2   NO2     19399 non-null  float64
 3   NOX     19388 non-null  float64
 4   O3      19493 non-null  float64
 5   SO2     16825 non-null  float64
 6   PM10    19207 non-null  float64
 7   PM2.5   1 non-null      float64
dtypes: float64(8)
memory usage: 1.6 MB
None
-------------------------------------------------- NOROESTE3
------------------------- Tipos de Datos
<class 'pandas.core.frame.DataFrame'>
Index: 743 entries, 0 to 742
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   CO      743 non-null    float64
 1   NO      743 non-null    float64
 2   NO2     743 non-null    float64
 3   NOX     743 non-null    float64
 4   O3      705 non-null    float64
 5   SO2     710 non-null    float64
 6   PM10    689 non-null    float64
 7   PM2.5   0 non-null      float64
dtypes: float64(8)
memory usage: 52.2 KB
None

Ahora se hará un análisis exploratorio de los datos con la limpieza ya realizada. Como primer putno se toma en cuenta las variables

In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import copy

# Lista de banderas inválidas (Tabla 3)
invalid_flags = ['p', 'c', 'd', 'b', 'm', 'l', 'z', 'o', 's', 'r', 'e', 'a', 'f', 'h', 'n', 'x']
all_quant_vars = ['CO', 'NO', 'NO2', 'NOX', 'O3', 'PM10', 'PM2.5', 'SO2', 'PRS', 'RAINF', 'RH', 'SR', 'TOUT', 'WSR', 'WDR']
key_vars = ['NO2', 'PM2.5', 'SO2']  # Variables clave para tráfico/refinería

# Función para analizar nulos y calidad
def analyze_dataset(dataset, dataset_name):
    print("="*80, f"{dataset_name}")
    null_summary = {}
    total_rows = 0
    valid_stations = []
    
    # Copia profunda para no modificar el original
    dataset_copy = copy.deepcopy(dataset)
    
    for station in dataset_copy:
        if station != 'CATÁLOGO':  # Ignorar CATÁLOGO
            df = dataset_copy[station].copy()
            
            # 1. Diagnóstico inicial: Verificar datos crudos
            print("-"*50, station)
            print("-"*25, "Datos Crudos (Primeras 5 filas)")
            print(df.head())
            print("-"*25, "Tipos de Datos Iniciales")
            print(df.info())
            print("-"*25, "Nulos Iniciales")
            null_counts_initial = df.isnull().sum()
            print(pd.DataFrame({'Nulos': null_counts_initial}))
            
            # Verificar valores únicos en columnas cuantitativas
            quant_vars = [col for col in all_quant_vars if col in df.columns]
            if not quant_vars:
                print(f"Advertencia: {station} no tiene variables cuantitativas. Omitiendo.")
                continue
            print("-"*25, "Valores Únicos")
            for col in quant_vars:
                print(f"{col}: {df[col].unique()[:10]}")  # Primeros 10 valores
            
            # Convertir a numérico
            for col in quant_vars:
                df[col] = pd.to_numeric(df[col], errors='coerce')
            
            # Contar nulos después de conversión
            print("-"*25, "Nulos después de Conversión")
            null_counts = df[quant_vars].isnull().sum()
            null_percent = (null_counts / df.shape[0] * 100).round(2)
            print(pd.DataFrame({'Nulos': null_counts, 'Porcentaje (%)': null_percent}))
            
            # Verificar banderas si existen
            if 'bandera' in df.columns:
                print("ENTRE A ESTE CICLO##################")
                print("-"*25, "Banderas")
                print(df['bandera'].value_counts())
                invalid_count = df['bandera'].isin(invalid_flags).sum()
                print(f"Datos con banderas inválidas: {invalid_count} ({invalid_count/df.shape[0]*100:.2f}%)")
                df = df[~df['bandera'].isin(invalid_flags)]
            
            # Aplicar reglas de Tabla 3
            df = df[df[quant_vars].ge(0).all(axis=1)]  # Negativos
            if 'PM10' in quant_vars and 'PM2.5' in quant_vars:
                print("ENTRE A ESTE CICLO################## PM10 PM2.5")
                df = df[df['PM2.5'] <= df['PM10']]  # PM2.5 ≤ PM10
                df = df[(df['PM10'] >= 5) & (df['PM2.5'] >= 5)]  # PM < 5
            if 'PM10' in quant_vars:
                print("ENTRE A ESTE CICLO################## PM10")
                df = df[df['PM10'] <= 900]  # PM10 > 900
            if 'CO' in quant_vars:
                df = df[df['CO'] >= 0.05]  # CO < 0.05
                print("ENTRE A ESTE CICLO################## CO")
            if 'TOUT' in quant_vars and 'PRS' in quant_vars:
                print("ENTRE A ESTE CICLO################## TOUT")
                df['temp_diff'] = df['TOUT'].diff().abs()
                df['pres_diff'] = df['PRS'].diff().abs()
                df = df[(df['temp_diff'].isna() | (df['temp_diff'] <= 10)) & 
                        (df['pres_diff'].isna() | (df['pres_diff'] <= 10))]
                df = df.drop(columns=['temp_diff', 'pres_diff'], errors='ignore')
            
            # Guardar DataFrame limpio en copia
            dataset_copy[station] = df
            total_rows += df.shape[0]
            null_summary[station] = {'counts': null_counts, 'percent': null_percent}
            valid_stations.append(station)
    
    # Resumen global
    print("-"*50, "Resumen Global")
    print(f"Total filas (tras limpieza): {total_rows}")
    total_nulls = sum([null_summary[station]['counts'].sum() for station in null_summary])
    print(f"Total nulos en variables cuantitativas: {total_nulls}")
    print(f"Porcentaje nulos global: {(total_nulls/(total_rows*len(quant_vars))*100):.2f}%")
    
    return null_summary, valid_stations, dataset_copy

# Analizar ambos datasets
null_summary_2023_2024, valid_stations_2023_2024, db_2023_2024_clean = analyze_dataset(db_2023_2024, "Dataset 2023-2024")
null_summary_2020_2022, valid_stations_2020_2022, db_2020_2022_clean = analyze_dataset(db_2020_2022, "Dataset 2020-2022")

# Función para generar el top de columnas con más nulos
def top_nulls(null_summary, dataset_name, top_n=5):
    print("="*80, f"Top Columnas con Más Nulos en {dataset_name}")
    # Aggregar nulos por columna a través de todas las estaciones
    aggregated_nulls = pd.DataFrame(null_summary).sum(axis=1)  # Sum nulos por columna
    aggregated_percent = pd.DataFrame({station: null_summary[station]['percent'] for station in null_summary}).mean(axis=1)  # Promedio % por columna
    
    # DataFrame con nulos y porcentajes agregados
    top_df = pd.DataFrame({'Nulos Totales': aggregated_nulls, 'Porcentaje Promedio (%)': aggregated_percent.round(2)})
    top_df = top_df.sort_values('Nulos Totales', ascending=False).head(top_n)  # Top N con más nulos
    
    print(top_df)
    top_df.to_csv(f'top_nulls_{dataset_name.replace(" ", "_")}.csv', index=True)
    
    return top_df

# Generar top para ambos datasets
top_2023_2024 = top_nulls(db_2023_2024_variablesImportantes, "Dataset 2023-2024")
top_2020_2022 = top_nulls(db_2020_2022_variablesImportantes, "Dataset 2020-2022")

# Comparar datasets
print("="*80, "Comparación de Datasets")
print("Porcentaje de nulos en variables clave (NO2, PM2.5, SO2):")
for station in set(valid_stations_2023_2024) & set(valid_stations_2020_2022):
    key_nulls_2023_2024 = null_summary_2023_2024[station]['percent'][key_vars]
    key_nulls_2020_2022 = null_summary_2020_2022[station]['percent'][key_vars]
    print(f"\nEstación: {station}")
    print("2023-2024:", key_nulls_2023_2024.to_dict())
    print("2020-2022:", key_nulls_2020_2022.to_dict())

# Decisión basada en nulos en key_vars
avg_nulls_2023_2024 = np.nanmean([null_summary_2023_2024[station]['percent'][key_vars].mean() 
                                  for station in valid_stations_2023_2024 
                                  if station in null_summary_2023_2024 and key_vars[0] in null_summary_2023_2024[station]['percent']])
avg_nulls_2020_2022 = np.nanmean([null_summary_2020_2022[station]['percent'][key_vars].mean() 
                                  for station in valid_stations_2020_2022 
                                  if station in null_summary_2020_2022 and key_vars[0] in null_summary_2020_2022[station]['percent']])
print("\nDecisión:")
if not np.isnan(avg_nulls_2023_2024) and not np.isnan(avg_nulls_2020_2022):
    if avg_nulls_2023_2024 < avg_nulls_2020_2022:
        print(f"Recomiendo usar db_2023_2024 para modelado (menos nulos: {avg_nulls_2023_2024:.2f}% vs. {avg_nulls_2020_2022:.2f}%)")
        print("Usa db_2020_2022 para EDA comparativo (COVID-19, políticas).")
    else:
        print(f"Recomiendo usar db_2020_2022 para modelado (menos nulos: {avg_nulls_2020_2022:.2f}% vs. {avg_nulls_2023_2024:.2f}%)")
        print("Usa db_2023_2024 para EDA comparativo.")
else:
    print("No se pudo calcular nulos promedio debido a datos faltantes. Revisa las estaciones.")

# Gráfico de frecuencias de promedios diarios
dfs = []
for station in db_2023_2024_clean:
    if station in valid_stations_2023_2024:
        df = db_2023_2024_clean[station].copy()
        df['estacion'] = station
        dfs.append(df)
for station in db_2020_2022_clean:
    if station in valid_stations_2020_2022:
        df = db_2020_2022_clean[station].copy()
        df['estacion'] = station
        dfs.append(df)
df_all = pd.concat(dfs, ignore_index=True)
df_all['date'] = pd.to_datetime(df_all['date'], format='%d/%m/%y %H:%M', errors='coerce')

# Promedios diarios por estación
df_all['date_day'] = df_all['date'].dt.date
daily_means = df_all.groupby(['date_day', 'estacion'])[key_vars].mean().reset_index()

# Histogramas y boxplots
for var in key_vars:
    plt.figure(figsize=(10, 6))
    sns.histplot(data=daily_means, x=var, hue='estacion', bins=30, kde=True, multiple='stack')
    plt.title(f'Histograma de Promedios Diarios de {var} por Estación')
    plt.savefig(f'hist_daily_station_{var}.png')
    plt.close()

    plt.figure(figsize=(10, 6))
    sns.boxplot(data=daily_means, y=var, x='estacion')
    plt.title(f'Boxplot de Promedios Diarios de {var} por Estación')
    plt.xticks(rotation=90)
    plt.savefig(f'box_daily_station_{var}.png')
    plt.close()

# Guardar dataset limpio
df_all.to_csv('dataset_descriptivo.csv', index=False)

================================================================================ Dataset 2023-2024
-------------------------------------------------- SURESTE
------------------------- Datos Crudos (Primeras 5 filas)
                 date    CO    NO   NO2   NOX   O3 PM10  PM2.5    PRS RAINF  \
0 2023-01-01 00:00:00  2.37  54.5  32.6  87.1    3  110     68  721.7     0
1 2023-01-01 01:00:00  2.12  38.7  30.3  68.9    3  116  67.18  721.5     0
2 2023-01-01 02:00:00  2.05  38.7  28.8  67.4    3  117  75.12  721.1     0
3 2023-01-01 03:00:00   2.5  60.5  29.1  89.4    3  135  82.81  720.8     0
4 2023-01-01 04:00:00  1.94  42.3  25.7  67.7  NaN  132  59.56  720.7     0

   RH  SO2 SR   TOUT  WSR  WDV
0  68  3.5  0  16.39  3.2  257
1  72  3.4  0  15.17  3.3  278
2  71  3.6  0  14.82  3.7  278
3  68  3.8  0  15.51  3.6  197
4  73  3.6  0  13.81  4.9  271
------------------------- Tipos de Datos Iniciales
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13870 entries, 0 to 13869
Data columns (total 16 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    13870 non-null  datetime64[ns]
 1   CO      13685 non-null  object
 2   NO      13504 non-null  object
 3   NO2     13717 non-null  object
 4   NOX     13716 non-null  object
 5   O3      13464 non-null  object
 6   PM10    13488 non-null  object
 7   PM2.5   10188 non-null  object
 8   PRS     13740 non-null  object
 9   RAINF   13738 non-null  object
 10  RH      13705 non-null  object
 11  SO2     13648 non-null  object
 12  SR      13811 non-null  object
 13  TOUT    13743 non-null  object
 14  WSR     13742 non-null  object
 15  WDV     13740 non-null  object
dtypes: datetime64[ns](1), object(15)
memory usage: 1.7+ MB
None
------------------------- Nulos Iniciales
       Nulos
date       0
CO       185
NO       366
NO2      153
NOX      154
O3       406
PM10     382
PM2.5   3682
PRS      130
RAINF    132
RH       165
SO2      222
SR        59
TOUT     127
WSR      128
WDV      130
------------------------- Valores Únicos
CO: [2.37 2.12 2.05 2.5 1.94 1.35 1.27 1.03 0.88 0.84]
NO: [54.5 38.7 60.5 42.3 10.2 7.8 5.4 5.1 6.9 8.5]
NO2: [32.6 30.3 28.8 29.1 25.7 23.1 22.5 15.4 12.4 13.5]
NOX: [87.1 68.9 67.4 89.4 67.7 33.2 30.3 20.8 17.4 20.3]
O3: [3 nan 4 10 13 16 17 24 31 53]
PM10: [110 116 117 135 132 96 59 61 47 27]
PM2.5: [68 67.18 75.12 82.81 59.56 33.58 34.65 24.32 14.34 8.14]
SO2: [3.5 3.4 3.6 3.8 3 3.3 3.2 nan 5.6 4.3]
PRS: [721.7 721.5 721.1 720.8 720.7 720.6 721.2 722.1 722.2 721.8]
RAINF: [0 nan 0.02 0.04 0.03 0.01 0.74 0.06 0.05 0.58]
RH: [68 72 71 73 59 51 39 37 28 24]
SR: [0 0.006 0.089 0.229 0.328 0.392 0.413 0.393 0.332 0.242]
TOUT: [16.39 15.17 14.82 15.51 13.81 13.65 14.04 15.49 16.59 19.97]
WSR: [3.2 3.3 3.7 3.6 4.9 6.8 8.4 10 11 9]
------------------------- Nulos después de Conversión
       Nulos  Porcentaje (%)
CO       185            1.33
NO       366            2.64
NO2      153            1.10
NOX      154            1.11
O3       406            2.93
PM10     382            2.75
PM2.5   3682           26.55
SO2      222            1.60
PRS      130            0.94
RAINF    132            0.95
RH       165            1.19
SR        59            0.43
TOUT     127            0.92
WSR      128            0.92
ENTRE A ESTE CICLO################## PM10 PM2.5
ENTRE A ESTE CICLO################## PM10
ENTRE A ESTE CICLO################## CO
ENTRE A ESTE CICLO################## TOUT
-------------------------------------------------- NORESTE
------------------------- Datos Crudos (Primeras 5 filas)
                 date    CO    NO   NO2    NOX O3 PM10 PM2.5    PRS RAINF  RH  \
0 2023-01-01 00:00:00   3.4  30.4    43   73.4  7  222   NaN  718.4     0  61
1 2023-01-01 01:00:00   4.3  67.2  44.4  111.6  8  311   NaN  718.1     0  61
2 2023-01-01 02:00:00  4.28  63.9  41.5  105.5  7  723   400  717.8     0  69
3 2023-01-01 03:00:00  3.77  57.2  42.3   99.5  6  473   349  717.6     0  72
4 2023-01-01 04:00:00  2.98  41.9  39.9   81.8  5  372   260  717.6     0  72

   SO2 SR   TOUT  WSR  WDV
0  3.8  0  19.01  4.1  190
1   24  0  17.32  1.4  222
2  9.8  0  16.22  2.5    4
3  7.8  0  15.57  1.6  330
4  7.3  0  15.53  4.1  343
------------------------- Tipos de Datos Iniciales
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13870 entries, 0 to 13869
Data columns (total 16 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    13870 non-null  datetime64[ns]
 1   CO      13282 non-null  object
 2   NO      13582 non-null  object
 3   NO2     13654 non-null  object
 4   NOX     13652 non-null  object
 5   O3      13198 non-null  object
 6   PM10    13434 non-null  object
 7   PM2.5   12314 non-null  object
 8   PRS     13627 non-null  object
 9   RAINF   13663 non-null  object
 10  RH      13527 non-null  object
 11  SO2     13474 non-null  object
 12  SR      13743 non-null  object
 13  TOUT    13637 non-null  object
 14  WSR     13658 non-null  object
 15  WDV     13644 non-null  object
dtypes: datetime64[ns](1), object(15)
memory usage: 1.7+ MB
None
------------------------- Nulos Iniciales
       Nulos
date       0
CO       588
NO       288
NO2      216
NOX      218
O3       672
PM10     436
PM2.5   1556
PRS      243
RAINF    207
RH       343
SO2      396
SR       127
TOUT     233
WSR      212
WDV      226
------------------------- Valores Únicos
CO: [3.4 4.3 4.28 3.77 2.98 2.1 3.04 1.81 2.31 2.22]
NO: [30.4 67.2 63.9 57.2 41.9 16.5 46.3 36.3 39.8 34.8]
NO2: [43 44.4 41.5 42.3 39.9 35.1 36.2 34.7 32.9 37.9]
NOX: [73.4 111.6 105.5 99.5 81.8 51.6 82.4 70.9 72.6 72.7]
O3: [7 8 6 5 4 11 21 34 43 47]
PM10: [222 311 723 473 372 285 173 212 125 144]
PM2.5: [nan 400 349 260 157 195 90 110 100 69]
SO2: [3.8 24 9.8 7.8 7.3 6 5.3 4.7 4.2 4.5]
PRS: [718.4 718.1 717.8 717.6 718 718.6 717.9 717 716 715.2]
RAINF: [0 nan 7.37 2.62 0.01 0.44 0.17 0.11 0.51 0.3]
RH: [61 69 72 70 71 63 60 46 33 29]
SR: [0 0.004 0.078 0.147 0.278 0.343 0.373 0.364 0.275 0.236]
TOUT: [19.01 17.32 16.22 15.57 15.53 15.18 14.9 15.68 14.15 18.7]
WSR: [4.1 1.4 2.5 1.6 5 4 4.4 2.3 0.7 1.9]
------------------------- Nulos después de Conversión
       Nulos  Porcentaje (%)
CO       588            4.24
NO       288            2.08
NO2      216            1.56
NOX      218            1.57
O3       672            4.84
PM10     436            3.14
PM2.5   1556           11.22
SO2      396            2.86
PRS      243            1.75
RAINF    207            1.49
RH       343            2.47
SR       127            0.92
TOUT     233            1.68
WSR      212            1.53
ENTRE A ESTE CICLO################## PM10 PM2.5
ENTRE A ESTE CICLO################## PM10
ENTRE A ESTE CICLO################## CO
ENTRE A ESTE CICLO################## TOUT
-------------------------------------------------- CENTRO
------------------------- Datos Crudos (Primeras 5 filas)
                 date    CO   NO   NO2   NOX  O3 PM10  PM2.5    PRS RAINF  RH  \
0 2023-01-01 00:00:00  1.67  4.1  30.3  34.5   9  118  94.12  718.4     0  45
1 2023-01-01 01:00:00   1.7    5  28.9  34.1   9   97  96.79  710.7     0  47
2 2023-01-01 02:00:00  1.51  4.3  23.2  27.7  11  103  81.23  710.4     0  46
3 2023-01-01 03:00:00   1.3  3.8  20.9  24.9  11   83  49.83  710.1     0  48
4 2023-01-01 04:00:00  1.28  4.6  20.7  25.5   9   65  40.19  710.2     0  55

   SO2     SR   TOUT  WSR  WDV
0  3.3      0  17.65  4.9  236
1  3.4  0.001  17.12  3.4  336
2  3.4  0.001  16.69  3.4    3
3  3.2  0.001  15.99  2.6  315
4    3  0.001  14.74  3.9  270
------------------------- Tipos de Datos Iniciales
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13870 entries, 0 to 13869
Data columns (total 16 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    13870 non-null  datetime64[ns]
 1   CO      13542 non-null  object
 2   NO      13100 non-null  object
 3   NO2     13537 non-null  object
 4   NOX     13535 non-null  object
 5   O3      13314 non-null  object
 6   PM10    13514 non-null  object
 7   PM2.5   11284 non-null  object
 8   PRS     13575 non-null  object
 9   RAINF   13601 non-null  object
 10  RH      13524 non-null  object
 11  SO2     13363 non-null  object
 12  SR      13782 non-null  object
 13  TOUT    13603 non-null  object
 14  WSR     13599 non-null  object
 15  WDV     13592 non-null  object
dtypes: datetime64[ns](1), object(15)
memory usage: 1.7+ MB
None
------------------------- Nulos Iniciales
       Nulos
date       0
CO       328
NO       770
NO2      333
NOX      335
O3       556
PM10     356
PM2.5   2586
PRS      295
RAINF    269
RH       346
SO2      507
SR        88
TOUT     267
WSR      271
WDV      278
------------------------- Valores Únicos
CO: [1.67 1.7 1.51 1.3 1.28 2.12 1.54 1.04 0.98 1]
NO: [4.1 5 4.3 3.8 4.6 19.8 7 3.7 6.5 6.2]
NO2: [30.3 28.9 23.2 20.9 20.7 30.6 23.7 13.6 12.3 14.9]
NOX: [34.5 34.1 27.7 24.9 25.5 50.6 30.8 17.6 16.3 21.7]
O3: [9 11 4 7 16 19 25 28 34 33]
PM10: [118 97 103 83 65 67 147 84 43 36]
PM2.5: [94.12 96.79 81.23 49.83 40.19 nan 108.13 35 13.23 12.31]
SO2: [3.3 3.4 3.2 3 3.1 3.5 6 9.9 2.7 6.5]
PRS: [718.4 710.7 710.4 710.1 710.2 710.6 711 711.2 711.1 709.9]
RAINF: [0 nan 0.85 0.04 0.01 0.54 0.31 0.19 0.22 0.73]
RH: [45 47 46 48 55 61 43 39 33 27]
SR: [0 0.001 0.007 0.028 0.087 0.457 0.586 0.652 0.634 0.549]
TOUT: [17.65 17.12 16.69 15.99 14.74 14.53 14.55 16.08 16.6 19.7]
WSR: [4.9 3.4 2.6 3.9 7.1 6.3 3.5 4.1 4.5 4.3]
------------------------- Nulos después de Conversión
       Nulos  Porcentaje (%)
CO       328            2.36
NO       770            5.55
NO2      333            2.40
NOX      335            2.42
O3       556            4.01
PM10     356            2.57
PM2.5   2586           18.64
SO2      507            3.66
PRS      295            2.13
RAINF    269            1.94
RH       346            2.49
SR        88            0.63
TOUT     267            1.93
WSR      271            1.95
ENTRE A ESTE CICLO################## PM10 PM2.5
ENTRE A ESTE CICLO################## PM10
ENTRE A ESTE CICLO################## CO
ENTRE A ESTE CICLO################## TOUT
-------------------------------------------------- NOROESTE
------------------------- Datos Crudos (Primeras 5 filas)
                 date    CO    NO   NO2    NOX O3 PM10 PM2.5    PRS RAINF  RH  \
0 2023-01-01 00:00:00  4.37  60.5  46.8  107.3  5  426   421  711.8     0  58
1 2023-01-01 01:00:00  2.88  30.1  42.1   72.2  4  393   362  711.5     0  59
2 2023-01-01 02:00:00  2.97  33.5  40.8   74.3  4  372   312  711.1     0  60
3 2023-01-01 03:00:00  3.15  47.6  38.5   86.1  4  260   222  710.9     0  63
4 2023-01-01 04:00:00  2.24  24.5  34.1   58.6  3  189   143  710.9     0  62

    SO2 SR   TOUT  WSR  WDV
0   5.6  0  18.37  5.5  327
1  12.8  0  17.93  7.2  322
2   9.4  0  17.08  6.4  316
3   6.1  0  16.24  6.1  327
4   5.6  0  16.03  6.9  326
------------------------- Tipos de Datos Iniciales
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13870 entries, 0 to 13869
Data columns (total 16 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    13870 non-null  datetime64[ns]
 1   CO      12270 non-null  object
 2   NO      11971 non-null  object
 3   NO2     12238 non-null  object
 4   NOX     12235 non-null  object
 5   O3      12614 non-null  object
 6   PM10    13128 non-null  object
 7   PM2.5   5407 non-null   object
 8   PRS     13253 non-null  object
 9   RAINF   13252 non-null  object
 10  RH      12829 non-null  object
 11  SO2     13042 non-null  object
 12  SR      13319 non-null  object
 13  TOUT    12716 non-null  object
 14  WSR     13252 non-null  object
 15  WDV     13244 non-null  object
dtypes: datetime64[ns](1), object(15)
memory usage: 1.7+ MB
None
------------------------- Nulos Iniciales
       Nulos
date       0
CO      1600
NO      1899
NO2     1632
NOX     1635
O3      1256
PM10     742
PM2.5   8463
PRS      617
RAINF    618
RH      1041
SO2      828
SR       551
TOUT    1154
WSR      618
WDV      626
------------------------- Valores Únicos
CO: [4.37 2.88 2.97 3.15 2.24 2.4 2.02 1.18 1.08 0.87]
NO: [60.5 30.1 33.5 47.6 24.5 31.8 26.6 5.4 3.5 5.2]
NO2: [46.8 42.1 40.8 38.5 34.1 32.3 28.7 23.7 20.1 14.8]
NOX: [107.3 72.2 74.3 86.1 58.6 64.1 55.3 29.2 23.6 20]
O3: [5 4 3 7 10 14 20 29 38 55]
PM10: [426 393 372 260 189 135 134 73 51 43]
PM2.5: [421 362 312 222 143 132 121 nan 4 2]
SO2: [5.6 12.8 9.4 6.1 5 5.2 5.4 4.7 4.9 4.1]
PRS: [711.8 711.5 711.1 710.9 711 711.9 712.1 712 711.4 710.6]
RAINF: [0 nan 0.4 0.2 4.6 1.6 2.4 0.6 5.4 5.6]
RH: [58 59 60 63 62 69 65 53 49 41]
SR: [0 0.013 0.13 0.275 0.404 0.496 0.529 0.51 0.444 0.333]
TOUT: [18.37 17.93 17.08 16.24 16.03 14.94 15.98 16.57 16.96 18.6]
WSR: [5.5 7.2 6.4 6.1 6.9 2.6 5.6 9.5 10.3 10]
------------------------- Nulos después de Conversión
       Nulos  Porcentaje (%)
CO      1600           11.54
NO      1899           13.69
NO2     1632           11.77
NOX     1635           11.79
O3      1256            9.06
PM10     742            5.35
PM2.5   8463           61.02
SO2      828            5.97
PRS      617            4.45
RAINF    618            4.46
RH      1041            7.51
SR       551            3.97
TOUT    1154            8.32
WSR      618            4.46
ENTRE A ESTE CICLO################## PM10 PM2.5
ENTRE A ESTE CICLO################## PM10
ENTRE A ESTE CICLO################## CO
ENTRE A ESTE CICLO################## TOUT
-------------------------------------------------- SUROESTE
------------------------- Datos Crudos (Primeras 5 filas)
                 date    CO    NO   NO2    NOX O3 PM10 PM2.5    PRS RAINF  RH  \
0 2023-01-01 00:00:00  3.67  53.1  40.6   93.6  8  221   NaN  701.2     0  55
1 2023-01-01 01:00:00   3.9  64.7    38  102.7  8  267   NaN  700.9     0  58
2 2023-01-01 02:00:00  4.28  77.7  35.7  113.4  8  320   NaN  700.6     0  58
3 2023-01-01 03:00:00  3.15    57  34.6   91.6  6  361   129  700.1     0  55
4 2023-01-01 04:00:00  2.32  26.9  31.8   58.7  6  166    74  700.1     0  52

   SO2 SR   TOUT  WSR  WDV
0  4.4  0  15.66  2.9  307
1  4.9  0  15.04  2.2  310
2  5.5  0  15.13  2.7  270
3  5.2  0  15.33  3.2  271
4  5.1  0  15.53  2.5  260
------------------------- Tipos de Datos Iniciales
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13870 entries, 0 to 13869
Data columns (total 16 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    13870 non-null  datetime64[ns]
 1   CO      13577 non-null  object
 2   NO      13369 non-null  object
 3   NO2     13354 non-null  object
 4   NOX     13354 non-null  object
 5   O3      13089 non-null  object
 6   PM10    13488 non-null  object
 7   PM2.5   11739 non-null  object
 8   PRS     13193 non-null  object
 9   RAINF   13582 non-null  object
 10  RH      13576 non-null  object
 11  SO2     13466 non-null  object
 12  SR      13635 non-null  object
 13  TOUT    13581 non-null  object
 14  WSR     13494 non-null  object
 15  WDV     13578 non-null  object
dtypes: datetime64[ns](1), object(15)
memory usage: 1.7+ MB
None
------------------------- Nulos Iniciales
       Nulos
date       0
CO       293
NO       501
NO2      516
NOX      516
O3       781
PM10     382
PM2.5   2131
PRS      677
RAINF    288
RH       294
SO2      404
SR       235
TOUT     289
WSR      376
WDV      292
------------------------- Valores Únicos
CO: [3.67 3.9 4.28 3.15 2.32 1.95 1.77 1.52 1.43 1.32]
NO: [53.1 64.7 77.7 57 26.9 24.8 19.5 24 8.1 18.8]
NO2: [40.6 38 35.7 34.6 31.8 32.2 27.1 25.9 22.2 23.5]
NOX: [93.6 102.7 113.4 91.6 58.7 57 46.6 49.9 30.3 42.3]
O3: [8 6 5 7 16 23 30 35 37 43]
PM10: [221 267 320 361 166 94 76 61 64 48]
PM2.5: [nan 129 74 54 42 45 30 22 23 12]
SO2: [4.4 4.9 5.5 5.2 5.1 4.7 4.5 4.2 4.1 4.8]
PRS: [701.2 700.9 700.6 700.1 700.2 700.3 700.5 700.8 701.4 699.8]
RAINF: [0 nan 0.16 0.07 0.25 0.02 0.03 0.01 0.11 0.06]
RH: [55 58 52 53 51 39 30 20 17 15]
SR: [0 0.002 0.126 0.273 0.4 0.487 0.52 0.474 0.432 0.329]
TOUT: [15.66 15.04 15.13 15.33 15.53 14.5 14.13 13.17 13.87 18.07]
WSR: [2.9 2.2 2.7 3.2 2.5 3.7 1.6 3.3 2.3 1.3]
------------------------- Nulos después de Conversión
       Nulos  Porcentaje (%)
CO       293            2.11
NO       501            3.61
NO2      516            3.72
NOX      516            3.72
O3       781            5.63
PM10     382            2.75
PM2.5   2131           15.36
SO2      404            2.91
PRS      677            4.88
RAINF    288            2.08
RH       294            2.12
SR       235            1.69
TOUT     289            2.08
WSR      376            2.71
ENTRE A ESTE CICLO################## PM10 PM2.5
ENTRE A ESTE CICLO################## PM10
ENTRE A ESTE CICLO################## CO
ENTRE A ESTE CICLO################## TOUT
-------------------------------------------------- NOROESTE2
------------------------- Datos Crudos (Primeras 5 filas)
                 date    CO    NO   NO2   NOX  O3 PM10   PM2.5    PRS RAINF  \
0 2023-01-01 00:00:00  2.07  31.6  40.6    72   7  398   221.6  700.3     0
1 2023-01-01 01:00:00  2.09  11.3  30.1  41.3   5  265  114.16  699.9     0
2 2023-01-01 02:00:00  2.17  39.4  31.7  70.9   5  167   84.92  699.4     0
3 2023-01-01 03:00:00  2.21  13.6    27  40.5   6  133   63.62  699.2     0
4 2023-01-01 04:00:00  2.15   6.1  16.4  22.5  10   86   29.06  699.2     0

   RH  SO2   SR   TOUT   WSR  WDV
0  53  2.1  NaN  15.93   4.6  306
1  53    2  NaN  14.96   6.2  298
2  54  2.1  NaN  14.51   3.4  295
3  55  2.1  NaN  14.23   7.1  305
4  52  2.2  NaN  14.23  12.3  303
------------------------- Tipos de Datos Iniciales
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13870 entries, 0 to 13869
Data columns (total 16 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    13870 non-null  datetime64[ns]
 1   CO      13548 non-null  object
 2   NO      13363 non-null  object
 3   NO2     13589 non-null  object
 4   NOX     13591 non-null  object
 5   O3      13437 non-null  object
 6   PM10    13543 non-null  object
 7   PM2.5   10719 non-null  object
 8   PRS     13598 non-null  object
 9   RAINF   13640 non-null  object
 10  RH      13534 non-null  object
 11  SO2     13400 non-null  object
 12  SR      10044 non-null  object
 13  TOUT    13639 non-null  object
 14  WSR     13640 non-null  object
 15  WDV     13634 non-null  object
dtypes: datetime64[ns](1), object(15)
memory usage: 1.7+ MB
None
------------------------- Nulos Iniciales
       Nulos
date       0
CO       322
NO       507
NO2      281
NOX      279
O3       433
PM10     327
PM2.5   3151
PRS      272
RAINF    230
RH       336
SO2      470
SR      3826
TOUT     231
WSR      230
WDV      236
------------------------- Valores Únicos
CO: [2.07 2.09 2.17 2.21 2.15 2.19 2.22 2.14 2.13 2.05]
NO: [31.6 11.3 39.4 13.6 6.1 5.5 5.2 5.3 6.5 7.2]
NO2: [40.6 30.1 31.7 27 16.4 16.3 15.8 17.6 17.4 12.6]
NOX: [72 41.3 70.9 40.5 22.5 21.7 21.1 22.9 23.9 19.7]
O3: [7 5 6 10 11 16 19 23 29 32]
PM10: [398 265 167 133 86 58 51 42 46 52]
PM2.5: [221.6 114.16 84.92 63.62 29.06 24.83 25.18 21.96 21.18 19.69]
SO2: [2.1 2 2.2 2.3 2.7 3.6 3.1 2.8 2.4 2.9]
PRS: [700.3 699.9 699.4 699.2 699.3 700.4 699.7 698.8 697.8 697.2]
RAINF: [0 nan 0.02 0.63 0.06 1.36 0.12 1.18 0.75 0.27]
RH: [53 54 55 52 50 49 45 43 33 26]
SR: [nan 0.287 0.288 0.3 0.32 0.301 0.333 0.268 0.282 0.312]
TOUT: [15.93 14.96 14.51 14.23 14.34 14.07 14.74 14.52 15.84 19.76]
WSR: [4.6 6.2 3.4 7.1 12.3 9.8 9.7 11.1 10 12.8]
------------------------- Nulos después de Conversión
       Nulos  Porcentaje (%)
CO       322            2.32
NO       507            3.66
NO2      281            2.03
NOX      279            2.01
O3       433            3.12
PM10     327            2.36
PM2.5   3151           22.72
SO2      470            3.39
PRS      272            1.96
RAINF    230            1.66
RH       336            2.42
SR      3826           27.58
TOUT     231            1.67
WSR      230            1.66
ENTRE A ESTE CICLO################## PM10 PM2.5
ENTRE A ESTE CICLO################## PM10

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

Histogramas o Boxplots: Para ver la distribución de cada gas en ambas estaciones (ej. ¿PM2.5 tiene más valores extremos en la industrial?).
Series temporales: Plotea gases vs fecha para detectar tendencias (ej. picos de NO2 en invierno).
Pairplot: Para explorar relaciones entre gases (ej. ¿CO y NOX están correlacionados por venir de combustión?).
Gráficos comparativos: Boxplots o barras para comparar medias de gases entre estaciones.

In [ ]:

# Comparar datasets
print("="*80, "Comparación de Datasets")
print("Porcentaje de nulos en variables clave (NO2, PM2.5, SO2):")
for station in set(valid_stations_2023_2024) & set(valid_stations_2020_2022):
    key_nulls_2023_2024 = null_summary_2023_2024[station]['percent'][key_vars]
    key_nulls_2020_2022 = null_summary_2020_2022[station]['percent'][key_vars]
    print(f"\nEstación: {station}")
    print("2023-2024:", key_nulls_2023_2024.to_dict())
    print("2020-2022:", key_nulls_2020_2022.to_dict())

# Decisión basada en nulos en key_vars
avg_nulls_2023_2024 = np.nanmean([null_summary_2023_2024[station]['percent'][key_vars].mean() 
                                  for station in valid_stations_2023_2024 
                                  if station in null_summary_2023_2024 and key_vars[0] in null_summary_2023_2024[station]['percent']])
avg_nulls_2020_2022 = np.nanmean([null_summary_2020_2022[station]['percent'][key_vars].mean() 
                                  for station in valid_stations_2020_2022 
                                  if station in null_summary_2020_2022 and key_vars[0] in null_summary_2020_2022[station]['percent']])
print("\nDecisión:")
if not np.isnan(avg_nulls_2023_2024) and not np.isnan(avg_nulls_2020_2022):
    if avg_nulls_2023_2024 < avg_nulls_2020_2022:
        print(f"Recomiendo usar db_2023_2024 para modelado (menos nulos: {avg_nulls_2023_2024:.2f}% vs. {avg_nulls_2020_2022:.2f}%)")
        print("Usa db_2020_2022 para EDA comparativo (COVID-19, políticas).")
    else:
        print(f"Recomiendo usar db_2020_2022 para modelado (menos nulos: {avg_nulls_2020_2022:.2f}% vs. {avg_nulls_2023_2024:.2f}%)")
        print("Usa db_2023_2024 para EDA comparativo.")
else:
    print("No se pudo calcular nulos promedio debido a datos faltantes. Revisa las estaciones.")

In [ ]:

# Gráfico de frecuencias de promedios diarios
dfs = []
for station in db_2023_2024_clean:
    if station in valid_stations_2023_2024:
        df = db_2023_2024_clean[station].copy()
        df['estacion'] = station
        dfs.append(df)
for station in db_2020_2022_clean:
    if station in valid_stations_2020_2022:
        df = db_2020_2022_clean[station].copy()
        df['estacion'] = station
        dfs.append(df)
df_all = pd.concat(dfs, ignore_index=True)
df_all['date'] = pd.to_datetime(df_all['date'], format='%d/%m/%y %H:%M', errors='coerce')

# Promedios diarios por estación
df_all['date_day'] = df_all['date'].dt.date
daily_means = df_all.groupby(['date_day', 'estacion'])[key_vars].mean().reset_index()

# Histogramas y boxplots
for var in key_vars:
    plt.figure(figsize=(10, 6))
    sns.histplot(data=daily_means, x=var, hue='estacion', bins=30, kde=True, multiple='stack')
    plt.title(f'Histograma de Promedios Diarios de {var} por Estación')
    plt.xlabel(var)
    plt.ylabel('Frecuencia')
    plt.savefig(f'hist_daily_station_{var}.png')
    plt.close()

    plt.figure(figsize=(10, 6))
    sns.boxplot(data=daily_means, y=var, x='estacion')
    plt.title(f'Boxplot de Promedios Diarios de {var} por Estación')
    plt.xticks(rotation=90)
    plt.savefig(f'box_daily_station_{var}.png')
    plt.close()

# Guardar dataset limpio
df_all.to_csv('dataset_descriptivo.csv', index=False)